wntrblm/nox

nox/main.py, tests/test_main.py
I found it difficult to get the escaping correct for parameterized
sessions. By returning an error I was able to debug this more easily.
(Also prevents me from thinking that I'm running tests when I'm actually
not.)
=> Log error when running session that doesn't exist.

appveyor.yml, nox/command.py, nox/utils.py, nox/virtualenv.py, tests/test_sessions.py, tests/test_utils.py, tests/test_virtualenv.py
Once complete, this PR will properly transform a standard `pythonX.Y` interpreter designation to the appropriate standard path on Windows.
At the moment, this is a "thrash PR" because AppVeyor is what I am using to test work. It is not yet intended for merge
Additionally, test coverage is below 100%. I am trying to figure out what code works properly before I write tests.
=> Properly transform interpreter on Windows

nox/main.py
I introduced a bug in #14 where `nox -f {relative_path}/nox.py` no longer works.
This fixes it. :-)
=> Fix relative paths to nox -f.

nox/main.py, tests/test_main.py
This comment makes it such that the global_config.noxfile argument is made an absolute path early in the process, which should prevent more tricky relative path issues.
Fixes the bug I introduced in #14 and failed to fix in #19. This time I actually _tested_ it on `google-cloud-python`.
=> Fix relative -f arguments.

CONTRIBUTING.md, docs/index.rst, docs/tutorial.rst, docs/usage.rst
Also fixing a "typo" in the usage doc where the wrong PyPI package (`nox`) was referred to. Now:
```
pip install --upgrade nox-automation[tox-to-nox]
```
=> Adding --upgrade to "pip install" instructions.

README.rst
Also managed to do some editorializing in the README :grinning: 
Currently the HTML generated [on PyPI][1] is:
```
<a href="docs" rel="nofollow">Read the Docs</a>
```
[1]: https://pypi.python.org/pypi/nox-automation/0.16.1
=> Fixing bad link in README (bad on PyPI).

docs/usage.rst
I noticed "session" appeared twice in contexts where it should be plural.
=> Changed some instances of session to be plural

.travis.yml, nox/_testing.py, nox/main.py, nox/manifest.py, nox/sessions.py, nox/tasks.py, nox/utils.py, nox/workflow.py, setup.py, tests/test_logger.py, tests/test_main.py, tests/test_manifest.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_workflow.py
Greetings.
I have a proposed refactoring that I would like to do (mostly done actually) regarding how nox comes up with its session list.
Right now, the `main` function discovers sessions based on the Noxfile, filters them based on CLI arguments, ends up with a `list`, and then does a simple loop over that list and executes them in order.
I want to refactor how nox stores its session list into a somewhat more powerful "manifest" class, implemented in this PR (`manifest.py`). The manifest takes the original list of functions that comes back from `discover_session_functions` and applies all the filters as before.
_Iterating_ over the manifest is slightly different, in an extremely important way. Internally, the manifest keeps a queue (a list of sessions yet to be yielded) and a consumed …
=> Refactor the list of sessions into a manifest class.

nox.py, nox/command.py, nox/manifest.py, nox/sessions.py, tests/test_command.py, tests/test_manifest.py, tests/test_sessions.py
This adds the `session.notify` command, exemplified in nox's own `nox.py` module, where any of the four interpreters trigger the `cover` session.
=> Addition of session.notify

nox/command.py
This way subclasses don't have to also set `__call__ = run`, they can just over-ride `run`.
**ASIDE 1**: @jonparrott Do you want me to write docstrings?
**ASIDE 2**: @jonparrott Is there a reason `InstallCommand` **does not** subclass `Command`?
**ASIDE 3**: I **would** label this as `hygiene`, but the label doesn't exist.
=> Making sure all `Command`s use run in `__call__`.

nox/main.py
=> Fix nox not returning a non-zero exit code on failure

nox/virtualenv.py, tests/test_virtualenv.py
On Windows, if the default strategy for finding a versioned interpreter fails, ask the `py.exe` launcher to locate it for us.
=> Locate the Python interpreter via the py.exe launcher

nox/virtualenv.py, tests/test_virtualenv.py
Follow-up to #53. Also
- Using single quotes instead of double quotes
- Adding Args/Returns section to docstring
=> Adding None-check to `locate_via_py`.

nox.py
This **was** the 2nd commit in #63, but I realize now that this change should go in now and the release should wait until we can confirm some things about 32-bit Python.
=> Adding coverage exemption for AppVeyor.

README.rst
Also changing the Travis badge text to read "Linux" (instead of "build").
Fixes #51.
----
Preview at: https://github.com/dhermes/nox/blob/add-appveyor-badge/README.rst
=> Adding AppVeyor badge to README.

docs/usage.rst, nox/manifest.py, tests/test_sessions.py
The extra is actually `tox_to_nox`, not `tox-to-nox`. Another acceptable way to "fix" this probably would be to rename the extra.
=> Fixing tox-to-nox docs reference.

requirements-test.txt, tests/conftest.py, tests/test__parametrize.py, tests/test_command.py, tests/test_main.py, tests/test_manifest.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_virtualenv.py, tests/test_workflow.py
Also sneaking in a missing license header on a file (I verified in the `git` history that the file is from 2016).
=> Simulating `unittest.mock` backport in the Python 2 standard library.

docs/usage.rst, nox/logger.py, nox/main.py
Default to nocolor when not running in a tty.
Resolves #78
=> Add --nocolor and --forcecolor options

docs/config.rst
You may want to consider using https://github.com/myint/rstcheck and/or running sphinx in nit-pick mode + fail on warnings http://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-n
=> Fix little python syntax error on docs

nox/virtualenv.py
@theacodes Do I need any tests for this?
=> Using `os.pathsep` instead of a hardcoded `':'`.

docs/usage.rst, nox/virtualenv.py, tests/test_virtualenv.py
An alternative implementation (and possibly a better one) would be to allow `arch` as an optional argument to `nox.session`. For example:
```python
@nox.session(python=["2.7", "3.7"], arch=["32", "64"])
def tests(session):
session.install("pytest")
session.install("-r", "requirements-dev.txt")
session.install("-e", ".")
session.run("py.test")
```
This would also give a "solution" to #60.
The real silly thing: I'm not sure anyone cares about 32-bit support. I used to test my OS X binaries for `bezier` in 32-bit, but then NumPy discontinued 32-bit support on OS X. Maybe that's a different beast since Apple controls the hardware?
=> Adding support for 32-bit binaries on Windows.

nox/virtualenv.py, tests/test_virtualenv.py
Also re-factoring unit tests to account for this change. This is a follow up to #100.
Also some minor editorializing (switch usage of `dir` to `dir_` as a variable name, shadowing builtins grumble grumble).
=> Storing `platform.system()` as global in `nox.virtualenv`.

nox/sessions.py, tests/test_sessions.py
This way old code being migrated will get failures when trying to set previously supported attributes such as `session.interpreter` and `session.virtualenv_dirname`.
----
Note that `TestSession.test_install` is currently broken because `Session.run` cannot be monkey-patched in the presence of `__slots__`. I have three workarounds for this in mind but would like to discuss:
1. Define the behavior of `Session.run` in a function `_run` defined in the `nox.sessions` module and the monkey-patch that function
1. Instantiate a do-nothing subclass of `Session` that does not have `__slots__`, then just monkey-patch `run` on that instance
1. Ditch `__slots__` and use `__(get|set|del)attr__` to give helpful error messages for non-existent attributes
=> Adding `Session.__slots__`.

CHANGELOG.md, docs/tutorial.rst, nox/sessions.py, nox/tasks.py, tests/test_virtualenv.py
Found the spelling errors with `codespell` using the command: `codespell nox/ docs/ tests/ *.py *.md *.rst --quiet-level=2`. Not sure if you'd like to add this to CI but I can do that as part of this PR if desired.
=> Documentation fixes, spelling, etc

docs/usage.rst, nox/__main__.py, nox/sessions.py, nox/virtualenv.py, tests/test_main.py, tests/test_sessions.py, tests/test_virtualenv.py
Note: This changes Nox's behavior. Previously, missing interpreters would cause a failed session. Now they just cause a warning. The previous behavior can be used via ``--error-on-missing-interpreters``.
Replaces #138 
Closes #136 
Releated #93
=> Skip sessions with missing interpreters

docs/config.rst, docs/usage.rst, nox/__init__.py, nox/__main__.py, nox/_options.py, nox/tasks.py, tests/test_main.py
Closes #141
@dhermes, @lukesneeringer I would appreciate a critical eye here. I'm not 100% sold on the way I did this internally.
=>  Add nox.options which allows specifying command-line configuration in the Noxfile

docs/config.rst, docs/usage.rst, nox/__main__.py, nox/_options.py, nox/command.py, nox/sessions.py, noxfile.py, tests/test_command.py, tests/test_main.py, tests/test_sessions.py
Add --warn-on-external-run flag and the "external" keyword arg to session.run.
Closes #130
=> Warn when programs not in the virtualenv are used, allow erroring and silencing the warning.

nox/manifest.py, tests/test_manifest.py
=> Run sessions in the same order specified on the command line.

nox/sessions.py, tests/test_sessions.py
Addresses #156 by checking if `silent` is in the kwargs passed to `session.install()`. If not, it sets it to the default True.
=> Allow silent argument to be set in session.install

docs/usage.rst, nox/__main__.py, nox/_options.py, nox/sessions.py, tests/test_main.py, tests/test_sessions.py
The main use is for downloading dependencies for later offline use (with `--reuse-existing-virtualenvs`). A typical session where this would be useful will have the form:
```python
@nox.session
def tests(session):
session.install(...)
session.run("spam", ...)
```
=> Add --install-only flag to install dependencies without running anything

docs/usage.rst, nox/__main__.py
This follows the informal standard defined at https://no-color.org, allowing users who don't want colour output from command line applications to set a single environment variable to disable it in all supported applications.
=> Don't colour output if `NO_COLOR` is set

nox/tasks.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_virtualenv.py
Our CI setup uploads the repo to the system's temporary directory, which on Linux is known(or commonly enough `/tmp`) but on windows, `%TEMP%` is used:
```
❯ bundle exec kitchen verify py3-windows-2012r2
-----> Starting Kitchen (v1.23.5)
-----> Verifying <py3-windows-2012r2>...
[Nox] Verify on instance py3-windows-2012r2 with state={:username=>"administrator", :auto_security_group_id=>"sg-0cf1cc52c2d0e5d24", :server_id=>"i-0f2b90b1cfedb970e", :hostname=>"10.27.2.213", :password=>"uDU9*;ZH(j", :last_action=
>"verify", :last_error=>nil}
Running Command: nox -f %TEMP%\kitchen/testing/noxfile.py -e "runtests-3(coverage=True)" -- --output-columns=120 --sysinfo --xml=%TEMP%\kitchen/testing/artifacts/xml-unittests-output --names-file=%TEMP%\kitchen\testing\tests\whiteli
st.txt --transport=zeromq …
```
=> Expand environment variables when loading the noxfile from provided path

docs/tutorial.rst, docs/usage.rst, nox/sessions.py, tests/test_sessions.py
I don't really know the reasoning why `--upgrade` was added by default to the `pip` call in `session.install`.
I would reason against it, but, since it has been the default, at least allow the user not to upgrade.
=> Allow not passing "--upgrade" to `session.install`

CHANGELOG.md, docs/CHANGELOG.md, docs/conf.py, docs/index.rst, requirements-test.txt
=> Include changelog in documentation

docs/tutorial.rst
Looks like Docker changed some links around and the old link is now only available when logged in. Changed the link to something which should work even for users without DockerHub accounts.
=> Fix documentation link for Docker Cloud vs Hub

docs/config.rst, nox/registry.py, tests/resources/noxfile_spaces.py, tests/test_main.py, tests/test_registry.py, tests/test_tasks.py
```python
import nox
@nox.session
def a_bar(session):
pass
@nox.session(name="not-a-bar")
def not_a_bar(session):
pass
```
```
$ nox -l
Available sessions:
* a_bar
* not-a-bar
```
=> Allow providing a friendlier CLI name to sessions.

nox/__main__.py, nox/manifest.py, nox/tasks.py, tests/test_main.py, tests/test_manifest.py, tests/test_tasks.py
=> Make --list list all available sessions, not just the selected ones.

nox/sessions.py, noxfile.py, tests/conftest.py
'pytest' is the recommended command since version 3.0. 
The command was called 'py.test' only for historical reasons:
https://docs.pytest.org/en/latest/faq.html#why-can-i-use-both-pytest-and-py-test-commands
Gratz on the project! 👍
=> Use 'pytest' instead of 'py.test' in examples and configuration

nox/__main__.py, nox/_option_set.py, nox/_options.py, nox/tasks.py, noxfile.py, tests/resources/noxfile_options.py, tests/test__option_set.py, tests/test_main.py, tests/test_sessions.py, tests/test_tasks.py
Closes #146, although there will need to be a follow up to use this information in the documentation.
=> Refactor how Nox defines and process options

.github/FUNDING.yml
The open collective key accepts a username.
Current URL looks like: https://opencollective.com/https://opencollective.com/python-nox
=> Fix funding external link

.travis.yml, docs/usage.rst, nox/_options.py, nox/sessions.py, noxfile.py, tests/test_main.py, tests/test_sessions.py
I took a stab at adding the interactive attribute to session. The tests are present, but I think it'll need some testing in a non-interactive pipeline to confirm it works. The unit tests in test_sessions feel a bit clunky with the mocks, so suggestions on making that cleaner would be great.
I need to sort out how to update the docs as well to include the new attribute.
If this looks reasonable to folks, I can take a look at adding the '--non-interactive' flag.
=> Add interactive property to session.

nox/tasks.py
Closes #212.
Python 3 deprecated imp.load_source and the entire imp package
has been deprecated since 3.4.
Same functionality served by importlib.machinery.SourceFileLoader,
see Brett Cannon back in 2012: https://bugs.python.org/issue14551
The load_module method provides a drop-in replacement for
load_source.
=> Replace imp.load_source() with importlib (#212)

nox/sessions.py
In order to fix #220 
I tried to succinctly implement option (2) from https://github.com/theacodes/nox/issues/220#issuecomment-513123726:
```
2. Make it clearer in docs what kinds of commands can and cannot be run, and point users to python commands like os.remove to help them along (ideally with example(s)). The burden to deal with asymmetries is with the user, but we help them along. Thanks @tswast for the pointers to those!
```
=> Document how to session.run builtins on Windows

.travis.yml, appveyor.yml, nox/registry.py, nox/sessions.py, nox/virtualenv.py, noxfile.py, requirements-conda-test.txt, tests/test_sessions.py, tests/test_virtualenv.py
* Add `session(venv_backend='conda')` option to use Conda environments.
* Add `session.conda_install()` function to install packages with
conda, instead of pip.
* Add `conda_tests` nox session to test `nox` with dependencies from
`conda-forge`.
* Add conda to Travis and Appveyor builds.
* Add `is_sandboxed` and `allowed_globals` to `ProcessEnv` classes.
Remove hardcoded index path.
Towards #199
Closes #183
Follow-up to https://github.com/theacodes/nox/pull/215 in order to get Travis to pick up the PR.
=> Add `session(venv_backend='conda')` option to use Conda environments.

nox/command.py, nox/logger.py, nox/manifest.py, nox/registry.py, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, noxfile.py
Type checking has lots of benefits for a codebase. I'm not sure if the lack of type checks in nox is intentional, but since nox supports Python 3.5+ it can use types. I went ahead and added mypy to the lint session and ignored all the existing mypy errors so it all passes. 
Future PRs can add more types to existing functions and gradually remove the ignored type checks. Of course if you aren't interested in types, feel free to decline this PR but it was something I would have benefited from as a newcomer trying to navigate the codebase, so I thought I'd put up a PR 😄 .
=> add mypy to lint

nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py, tests/test_virtualenv.py
This PR adds support for a different backend, `venv`. It adds a keyword argument to the `VirtualEnv` class, which defaults to `False` and is only true when the nox session has `venv_backend=True`.
It also updates the resolution of the Python path, since using `venv` alone does not fix issues when creating a venv from within a virtual environment.
The path resolution is modified to determine if a virtual environment is being used. If so, it tries to find the desired Python interpreter version in the `base_prefix` rather than anywhere on the system's PATH. Note that Windows was not tested, and probably will require some more changes.
```
cd ~/git/nox
pip install -e .
cd ~/git/pipx
nox -s unittests-3.6  # tests pass
```
> prefix: A string giving the site-specific directory prefix where the …
=> add venv as an option for venv_backend

docs/usage.rst, nox/_option_set.py, nox/_options.py, setup.py, tests/test__option_set.py
To try this out in bash run the following. Other shells also have limited support. See instructions in the docs in this PR.
```
pip install .  # from nox directory since a new dependency is required
eval "$(register-python-argcomplete nox)"
nox <tab>
nox --<tab>
nox -s <tab>
```
A sample of the autocompletions for all items that start with a `--`:
The  `_session_completer` function provides a list of sessions when hitting tab in `nox -s <tab>`. argcomplete provides `parsed_args` to this function, which is the Namespace argparse would have returned if the program were actually run. This corresponds almost directly to nox's global_config, and it works out of the box :smile: .
Note that this adds a new dependency to nox in setup.py, `argcomplete`.
fixes …
=> add shell autocomplete

nox/virtualenv.py, tests/test_virtualenv.py
To fix #219 
TL;DR: Trying to implement the suggestion in https://github.com/theacodes/nox/issues/219#issuecomment-512933886, this PR adds a final check at the end of the property ``nox.virtualenv._resolved_interpreter`` which looks for an interpreter called "python" in the ``PATH``, checks whether its ``--version`` fits the required version, and returns it as the resolved interpreter if it matches.
As described in #219, sessions specifying the interpreter version (e.g. ``@nox.session(python='3.7')``) don't find the existing matching python 3.7 if it is called "python" or "python.exe" and no python launcher ("py.exe") is available.
The same sessions work when not specifying python='3.7', even if the used interpreter is actually python 3.7. If this happens, it makes it harder for …
=> Resolve to interpreter 'python' in PATH if '--version' fits

.flake8, nox/_option_set.py, nox/_options.py, tests/test_main.py
This PR adds changes to raise an error if an unknown argument is passed.
```
nox lint 
> nox 
nox > Running session tests-3.5
nox > Session tests-3.5 skipped: Python interpreter 3.5 not found.
nox > Running session tests-3.6
...
```
```
>> nox lint
usage: nox [-h] [--version] [-l] [-s [SESSIONS [SESSIONS ...]]] [-k KEYWORDS]
[-r] [--no-reuse-existing-virtualenvs] [-f NOXFILE]
[--envdir ENVDIR] [-x] [--no-stop-on-first-error]
[--error-on-missing-interpreters]
[--no-error-on-missing-interpreters] [--error-on-external-run]
[--no-error-on-external-run] [--install-only] [--report REPORT]
[--non-interactive] [--nocolor] [--forcecolor]
...
nox: error: Unrecognized argument(s): 'lint'
>> nox -s lint
nox > Running session lint
nox > Creating virtualenv using python3.7 in .nox/lint
...
```
fixes …
=> immediately exit if unknown arguments are passed

docs/usage.rst, nox/__main__.py, nox/_options.py, nox/command.py, nox/logger.py, tests/test_command.py, tests/test_logger.py
=> Allow showing the commands output

noxfile.py, requirements-conda-test.txt
Towards #234 
The `argcomplete` dependency was added in #228, but not to the conda dependencies, which broke the `conda_tests` sessions (not currently tested from CI, as it just runs the same tests as in the `tests` sessions, but downloading dependencies via conda, instead.
=> Add argcomplete dependency to conda test session.

nox/virtualenv.py
Add the `VIRTUAL_ENV` variable to the process environment of commands executed in a nox session. The value of this variable contains the location of the virtualenv created by nox. 
Closes #159
**Rationale**
Some commands rely on the presence of the `VIRTUAL_ENV` variable in their environment to detect that they are running in a virtualenv. In particular, [poetry](https://poetry.eustace.io) and [pipenv](https://github.com/pypa/pipenv) will only install packages into the virtualenv if its location is passed to them via this variable. Without that variable, these commands will create their own virtualenv for the project, breaking session isolation.
The `VIRTUAL_ENV` variable is set in the user's shell by the `bin/activate` scripts provided with virtual environments created by `virtualenv` …
=> Pass VIRTUAL_ENV environment variable to commands

nox/__main__.py, nox/command.py, nox/sessions.py, nox/tasks.py, nox/virtualenv.py, noxfile.py, setup.py, tests/test__option_set.py, tests/test__parametrize.py, tests/test_command.py, tests/test_main.py, tests/test_manifest.py, tests/test_registry.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_tox_to_nox.py, tests/test_virtualenv.py
There is no easy way to automatically satisfy flake8's linting requirements for sort order. Using isort there is.
I ran 
```
isort --recursive nox
```
to automatically sort imports. Then I updated noxfile to test with isort rather than flake8.
=> replace flake8 sorter with isort

nox/_option_set.py, nox/_options.py, tests/test__option_set.py
Ran `monkeytype apply nox._option_set` then added additional types as needed.
=> add types to _option_set.py

docs/config.rst, docs/usage.rst, nox/sessions.py
This was causing a weird thing here https://nox.thea.codes/en/latest/usage.html#controling-commands-verbosity
(replacing the `--` for an en-dash).
I searched the whole docs and docstrings.
=> Use double ` for inline code

appveyor.yml
This ordering helps identify when a problem occurs only
in older versions of Python, as AppVeyor fail-fast means
failures in the early jobs prevent seeing if latter jobs
would have succeeded.
=> appveyor.yml: Order Pythons in descending version

docs/tutorial.rst
Without `pip` users will see: `No module named install`
=> Fix example installation call for pip

nox/_options.py, tests/test_main.py
Currently checks stdin
Fixes #266
=> Use stdout.isatty to finalize color

docs/config.rst
This very minor PR corrects a syntax highlighting issue in the docs.
=> Syntax highlighting fix in configuration docs

.travis.yml, CONTRIBUTING.md, appveyor.yml, docs/config.rst, noxfile.py, setup.py
Hi everyone,
Since I work on my projects using nox and python3.8, I think it's wise to point out that nox also works with python3.8, hence my pull request.
=> Support for Python 3.8

nox/tasks.py
I had a `noxfile.py` which looked something like:
```
import os
os.makedirs(some_already_existing_path)
....
```
While running this with `nox`, I kept running into an odd:
```
nox > Noxfile /home/me/noxfile.py not found
```
Pretty sure the file was there and I also checked the file permissions and other usual suspects. Couldn't make much sense out of it so looked into the source code of `nox` and realized that this error message is inaccurate. In fact, this has been reported as an issue at https://github.com/theacodes/nox/issues/248.
The commit in this PR, changes the log message to more accurately describe what went wrong and also include a trace back of the actual exception to help diagonize the issue. Any reviews/suggestions?
P.S: I took the liberty to open this PR since it's been a …
=> Use a more accurate error message if loading of noxfile runs into error

nox/py.typed, setup.py
Because nox is not marked as containing type hints, any libraries that import nox will get a mypy error saying the library is untyped. To fix this, users have had to do
```
import nox  # type: ignore
```
to avoid errors such as
```
error: Cannot find implementation or library stub for module named 'nox'
note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
```
This PR implements instructions in the mypy documentation to tell mypy that nox does indeed have inline types (https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages). Though rather strange and arbitrary, this is the standard way to do this. GvR himself committed a py.typed to mypy [here](https://github.com/python/mypy/blob/master/mypy/py.typed).
If this code is …
=> enable type hints when importing nox

docs/conf.py, nox/__main__.py, setup.py, tests/test_main.py
=> Prefer importlib.metadata for metadata loading.

.coveragerc, .gitignore, .isort.cfg, nox/__main__.py, nox/_option_set.py, nox/_options.py, nox/_parametrize.py, nox/_typing.py, nox/command.py, nox/logger.py, nox/manifest.py, nox/popen.py, nox/registry.py, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, nox/workflow.py, noxfile.py, tests/test_main.py
Since more typehints are desired, #276, I have added typehints to support the `--disallow-untyped-defs` flag. The change set is large, as I've added annotations so all functions have them. For the most part the change set only includes:
-   Add the required `typing` imports.
-   Add [function annotations](https://www.python.org/dev/peps/pep-3107/) to all functions.
-   Add and update some [type comments](https://www.python.org/dev/peps/pep-0484/#type-comments).
-   Ignore typehints, "type: ignore", which can't be solved by the above solutions.
Even though all functions have been hinted, this is by no means a complete solution. There are lots of errors being ignored, with a significant amount being around how you bind things like `python` to a `Callable`. There's also a lack of generics, …
=> Upgrade typehints to support disallow-untyped-defs flag

nox/_decorators.py, nox/_parametrize.py, nox/_typing.py, nox/manifest.py, nox/registry.py, nox/sessions.py, noxfile.py, tests/test__parametrize.py, tests/test_manifest.py
Hey, sorry for the delay.  
I have improved typing as discussed in #287. I have:
-   Updated the `noxfile.py` to include the `--warn-unused-ignores` flag.
-   Made a `_decorators` file, as the code started to call and inherit from multiple different files. This was causing some cyclical dependencies.
-   Changed [`_parametrize.generate_calls`](https://github.com/theacodes/nox/blob/1bd08bc7d85f7276b07a72b720c673a5df384188/nox/_parametrize.py#L172) to a class decorator, `Call`.
-   Changed [`registry.session_decorator`](https://github.com/theacodes/nox/blob/1bd08bc7d85f7276b07a72b720c673a5df384188/nox/registry.py#L24) to delegate to a class decorator, `Func`.
-   Moved [`manifest._copy_func`](https://github.com/theacodes/nox/blob/1bd08bc7d85f7276b07a72b720c673a5df384188/nox/manifest.py#L26) …
=> Convert function decorators to class decorators

nox/__main__.py, nox/_option_set.py, nox/_parametrize.py, nox/_typing.py, nox/command.py, nox/logger.py, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, noxfile.py, tests/test__parametrize.py, tests/test_virtualenv.py
Hey, I have started work on #292. In this PR I have updated the code to be able to remove the `# type: ignore` from 1.1, 1.2, 1.4, 1.5 and I have fixed an incorrect typing for [`ProcessEnv.allowed_globals`](https://github.com/theacodes/nox/blob/8869bf2a20d51343e76459ca50ae2dc36d2b46e2/nox/virtualenv.py#L160).
Since 1.1 touches a lot of files and since 1.2 was a bit more complex than I originally thought, I've stopped here. The other changes should be fairly trivial.
This leaves 1.3, 1.6 and all of 2 to be done.
=> Remove some type ignores

noxfile.py
Fixes #295 - due to a bug in Python 3.6.0 coverage fails to run successfully.
=> Don't run coverage on 3.6.0

.gitignore, docs/config.rst, docs/usage.rst, nox/_options.py, nox/manifest.py, nox/tasks.py, tests/test_manifest.py, tests/test_tasks.py
=> Add ability to specify which Python versions to run with from the command line

nox/sessions.py, noxfile.py, tests/test_sessions.py
This doesn't have docs or tests! Hooray :)
It does however show one way to implement it (kinda hacky) and a working use case for further discussion.
=> Address #319: Give a create_tmp API

docs/config.rst, docs/usage.rst, nox/_decorators.py, nox/_options.py, nox/manifest.py, nox/sessions.py, nox/tasks.py, nox/virtualenv.py, tests/resources/noxfile_pythons.py, tests/test__option_set.py, tests/test_main.py, tests/test_manifest.py, tests/test_sessions.py, tests/test_tasks.py
Changelog (let me know if I should commit it in the changelog file):
- New global option `nox.options.default_venv_backend` to set the default backend. Fixes #315 
- New global option `nox.options.force_venv_backend` to temporarily force the backend. The commandline version of this option will probably be used more frequently than the noxfile one, but thanks to the great generic option mechanism built in nox, I got both for the same price :) . Fixes #317
- Added possibility to declare a "no backend / passthrough" venv with `venv_backend='none'` (or to force it temporarily with the `--no-venv` cli option, equivalent to `--force-venv-backend none`, see above). Fixes #301
- Now `install` and `conda_install` work when there is no venv backend (or python=False). Previously a `ValueError` was …
=> `venv_backend` new options and choices

docs/index.rst, docs/tutorial.rst, nox/sessions.py, tests/test_sessions.py
=> Add `Session.run_always()`.

nox/__main__.py, nox/_options.py, nox/logger.py, tests/test_logger.py
introducing an --add_timestamp flag and support for in in the logging system.
#289
=> draft: --add-timestamp

nox/command.py, nox/sessions.py, nox/virtualenv.py, tests/test_command.py, tests/test_sessions.py, tests/test_virtualenv.py
Changelog (should I commit it in the changelog file ?)
- Virtual environments now have a `bin_paths` attribute instead of a single `bin`. `command.run` and `which` both have their `path` argument renamed `paths` and supporting a list of paths, to handle it. 
- Fixed the default paths for conda on windows where the `python.exe` found was not the correct one. Fixes #256
=> Fixed the default paths for conda on windows where the `python.exe` found was not the correct one

nox/sessions.py, tests/test_sessions.py
Changelog (let me know if I should commit it somewhere):
- `conda_install` ~~and `install`~~ args are now automatically double-quoted when they contain a `<` or a `>`. Fixes #311
=> `conda_install` and `install` args are now automatically double-quoted when needed.

.coveragerc, .travis.yml, nox/registry.py
Previously the decorator would obscure the
function type.
=> Fully annotate the session decorator

nox/_option_set.py
Fixes #356 
When merging options specified in the noxfile and on the command-line, do not use the output parameter `command_args` as the input for the merge. Instead, copy `command_args` initially and pass the copy to the merge functions.
Merge functions such as `_session_filters_merge_func` inspect `command_args` to see if other options have been specified on the command-line. When the options are merged in place, this check produces false positives.
For example, `nox.options.sessions` is copied into `command_args` as a part of the merge. So it will appear to have been specified on the command-line when merging `nox.options.pythons`, causing the latter to be ignored.
=> Do not merge command-line options and nox.options in place

nox/_options.py, tests/resources/noxfile_options_pythons.py, tests/test_main.py
Closes #358 
This PR is a follow-up to #357, and contains the following additional changes:
**1. Do not ignore nox.options.pythons when --{sessions,keywords} passed**
Declare the `--python` option without a custom merge function, i.e. omit the `merge_func` parameter. As a result, `nox.options.pythons` will no longer be ignored when `--sessions` or `--keywords` are passed.
**2. Do not ignore nox.options.{sessions,keywords} when --pythons passed**
Revert `_session_filters_merge_func` to the state before `--pythons` was introduced. This means that it will only check if `--sessions` or `--keywords` were specified on the command-line. As a result, the `nox.options.sessions` and `nox.options.keywords` settings will no longer be ignored when `--pythons` is passed.
=> Decouple merging of --python with nox.options from --sessions and --keywords

nox/virtualenv.py, tests/test_virtualenv.py
This fixes an issue where "3.10" is resolved as "python3", as demonstrated by the test case.
<details>
<summary>
Test failure
</summary>
```
==================================================================================== FAILURES ====================================================================================
_______________________________________________________ test__resolved_interpreter_numerical_non_windows[3.10-python3.10] ________________________________________________________
sysfind = <MagicMock name='sysfind' id='4339276912'>, make_one = <function make_one.<locals>.factory at 0x102a6e790>, input_ = '3.10', expected = 'python3.10'
@pytest.mark.parametrize(
["input_", "expected"],
[
("3", "python3"),
("3.6", "python3.6"),
("3.6.2", "python3.6"),
("3.10", "python3.10"), …
```
=> Support double-digit minor version in `python` keyword

noxfile.py
This came up in the context of #364:
> Thanks! I think we can add this check in the lint step (`isort --check`)
> 
> https://github.com/theacodes/nox/blob/495b23ff690049e8f3d25f3d29c06458da2ee274/noxfile.py#L82
> 
> Compatible settings are in https://github.com/psf/black/blob/master/docs/compatible_configs.md#isort
> 
> That can be done in another PR of course, CI failure looks unrelated
@stsewd Nox's `.isort.cfg` contains all of the compatible configuration settings you linked to, with the exception of `ensure_newline_before_comments = True`. I did not bother to add that setting to the configuration file because isort 5 has a black profile, rendering manual configuration unnecessary once we upgrade.
=> Add isort check to lint session

nox/registry.py
Type checkers cannot solve an aliased, generic callable.
=> Fix nested decorator annotation

.travis.yml, docs/config.rst, docs/usage.rst, nox/sessions.py, tests/test_sessions.py
Closes #262 
- Refactored `pip` as `python -m pip`. Since It is a good practice.
@theacodes  Please review 😃
=> Refactor pip as python -m pip

nox/virtualenv.py
Closes https://github.com/theacodes/nox/issues/372.
=> Use conda remove to clean up existing conda environment

nox/logger.py
This errors when running `nox -v`.
That method is making use of `_simple_fmt`,
but isn't defined in the class.
I used the same value as `NoxFormatter`
=> Fix NoxColoredFormatter.format

nox/sessions.py, tests/test_sessions.py
os.chdir() has supported PathLib since Python 3.6.
Discovered while adding types pip's noxfile.py:
https://github.com/pypa/pip/pull/9411
=> Allow passing PathLike types to Session.chdir()

nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py, tests/test_virtualenv.py
The property now never returns None. This simplifies user code containing
types that already knows a bin directory must exist. It avoids the need
to pepper calling code with:
assert session.bin is not None
Or
For example, in pip:
https://github.com/pypa/pip/blob/062f0e54d99f58e53be36be5a45adad89e2429fb/tools/automation/release/__init__.py#L29
A noxfile that tries to access a bin directory that doesn't exist will
now raise an exception.
=> Make ProcessEnv.bin always return a str

nox/virtualenv.py
Fixes errors when running mypy on a project's noxfile.py:
noxfile.py:42: error: "ProcessEnv" has no attribute "location"
Discovered while adding types pip's noxfile.py:
pypa/pip#9411
=> Define the location attribute on base class ProcessEnv

docs/config.rst, docs/usage.rst
=> Docs: remove outdated notes on Windows compatibility 

nox/popen.py, tests/test_command.py
Based on my comments in the issue #309 I created a decoding wrapper function. As `utf8` is the python default I kept it hard coded as first choice of the encodings to try. If `utf8` fails `sys.stdout.encoding`, `sys.getdefaultencoding()` and `locale.getpreferredencoding()` (in this order) deliver possible other encodings to try. If all decoding attempts fail the `UnicodeDecodeError` exception is risen.
I'm open for other orders of the encoding sources.
If this fix is well received, I will add the missing tests and fix the broken ones if there are any.
fixes #309
=> Decode popen output using the system locale if UTF-8 decoding fails.

nox/sessions.py, tests/test_sessions.py
Being able to know what session you are in is useful for a variety of reasons. One of which is to be able to name artifacts in a way that is traceable back to the session, such as with [code coverage reports](https://stackoverflow.com/q/66170792/1485877). Right now, the only solution is to dig down to `session._runner.friendly_name`:
```python
import nox
@nox.session(python=['3.6', '3.7', '3.8', '3.9'])
def test(session):
session.install('.')
session.install('pytest', 'pytest-cov')
session.env['COVERAGE_FILE'] = f'.coverage.{session._runner.friendly_name}'
session.run('python', '-m', 'pytest', '--cov', 'tests/')
```
This PR exposes that private attribute via a public property:
```python
import nox
@nox.session(python=['3.6', '3.7', '3.8', '3.9'])
def test(session):
session.install('.') …
```
=> Add `Session.name`

docs/config.rst, nox/__init__.py, nox/__main__.py, nox/_version.py, nox/tasks.py, setup.py, tests/test__version.py, tests/test_tasks.py
Exit with a friendly error if the Nox version does not satisfy the requirements
specified by the user's Noxfile in `nox.needs_version`:
- Add dependency on [packaging] to Nox `install_requires`
- Add `nox.needs_version` attribute with [PEP 440] version specifiers for Nox
- Add `nox._version` module with these functions and classes:
- function `get_nox_version`
- function `check_nox_version`
- exception `VersionCheckFailed`
- exception `InvalidVersionSpecifier`
- Adapt `tasks.load_nox_module` to invoke `check_nox_version`
- Refactor `__main__` to use `get_nox_version` for `--version` option
- Tests and documentation
Closes #99
Supercedes #210
Some words about the approach taken here:
1. Rather than a minimum required version, `needs_version` accepts any [PEP 440]
version specifier. Mostly, …
=> Add nox.needs_version to specify Nox version requirements

nox/popen.py, tests/test_command.py
Fixes #139
This PR changes Nox's behavior when receiving a keyboard interrupt (CTRL-C, `SIGINT`) while executing a command with `session.run` or `session.install`.
The current behavior is to terminate the child immediately (`SIGTERM` on Posix, `TerminateProcess` on Windows) and to reraise the `KeyboardInterrupt`, ultimately exiting with failure.
The new behavior is to shut down the child gracefully and only raise if the child did not exit with success. The shutdown sequence consists of these four steps:
1. Check if the child has terminated, with a 300ms timeout. If it did, skip to the last step. Note that the OS delivers the signal to the child as well.
2. Send `SIGTERM` and check again, with a 200ms timeout. If it did, skip to the last step.
3. Send `SIGKILL` and wait without timeout.
4. …
=> Gracefully shutdown child processes

CONTRIBUTING.md
#389 replaces Travis with GitHub actions. This PR removes Travis references from the docs.
---
Thanks!
=> Remove Travis references from docs

noxfile.py
Nox does not have a `mypy.ini` or `setup.cfg`. This will cause mypy to look for configuration files [in other directories](https://mypy.readthedocs.io/en/stable/config_file.html), which can cause failures when testing locally. This PR adds the `--config-file=` argument, which tells mypy to ignore config files.
---
Thanks!
=> Ignore mypy configuration file

nox/_parametrize.py, tests/test__parametrize.py
Parameterized jobs will now display in the same order as they are written.
```python
"""Example noxfile.py"""
import nox
@nox.session()
@nox.parameterize(
("z", "a"),
[
(1, 2),
(3, 4),
]
)
def job(z, a):
...
```
```sh
% nox --list
* job(a=2, z=1)
* job(a=4, z=3)
```
```sh
% nox --list
* job(z=1, a=2)
* job(z=3, a=4)
```
Closes #264
---
Thanks for the great library!
=> Preserve the order of parameterized arguments

nox/manifest.py, nox/sessions.py, tests/test_manifest.py, tests/test_sessions.py
Closes: https://github.com/theacodes/nox/issues/391
Once the basic API has been reviewed and accepted I'll add tests for this feature.
=> set local session posargs via notify

nox/virtualenv.py, tests/test_virtualenv.py
This is an attempt to fix #123 
The steps are the following
- Check virtualenv interpreter
- Check current interpreter
- If there is a match, do nothing. If they are different, recreate
- Check if the type of interpreter remains the same.
Not sure, but for the last case I made an assertion.
=> Check whether interpreter changed and type (#123)

nox/virtualenv.py, tests/test_virtualenv.py
Fixes #419 by moving 'pip' to after venv_params
=> fix position of venv_params within conda create

nox/manifest.py, tests/test_manifest.py
First of all, thanks for this amazing tool, I started to use it recently (I come from the `tox` world)
This is a possible fix for (#396):
- Attempt to do the previous checks
- On fail, it will normalize arguments using ast (based on discussion)
- The comparison will be on ast representation of the strings
- Add unit tests
=> Add normalized comparison to check sessions (#396)

docs/config.rst, nox/_decorators.py, tests/test__parametrize.py
=> Allow nox.parametrize to select the session Python

nox/virtualenv.py, tests/test_virtualenv.py
=> Fix regression in check for stale environments

noxfile.py, requirements-test.txt, tests/test_main.py
The contexter package is a third-party backport of contextlib (with some
extensions). It is no longer required because Nox does not support Python 2
anymore, and we only ever used the standard ExitStack interface.
The contexter package was used only in the test suite.
Supercedes #421
=> Drop contexter from test requirements

nox/virtualenv.py, tests/test_virtualenv.py
_Follow-up to #418 and #425_
This PR contains two changes to the staleness check when reusing environments:
**1. Fix environments not being reused due to wrong Python lookup**
When determining the Python base installation of an existing environment, allow `nox.command.run` to find the Python executable in the virtualenv, by passing `VirtualEnv.bin_paths` as the `paths` argument.
The original PR (#418) passed `os.path.join(self.location, "bin", "python")`. This does not work for two reasons:
- The directory is named "Scripts" on Windows.
- The executable is named "python.exe" on Windows.
The follow-up PR (#425) passed bare "python". This does not work, because `nox.command.run` searches `PATH` by default. It needs to be told to search the virtualenv instead.
This fix exposed portability …
=> Fix environments not being reused due to wrong Python lookup

setup.py
5 is the latest release, and 6.x just drops support for Python 2, so we should be good.
Fixes #430
=> Allow colorlog <7.0.0

docs/usage.rst, nox/_options.py, tests/test_main.py
This PR adds an option `--force-python` / `--force-pythons` which functions as a shorthand for when the same interpreter spec should be passed to both `--python` and `--extra-python`. This has the effect of running sessions on the specified interpreter *instead* of those listed for each session.
In other words, these two are equivalent:
- `nox --python=X.Y --extra-python=X.Y`
- `nox --force-python=X.Y`
By comparison, `--extra-python` on its own adds an interpreter to those listed for a session. The sessions will be run on the original Python versions *as well as* the extra version.
This came up a few times in the past:
- https://github.com/theacodes/nox/pull/361#issuecomment-748300867
- https://github.com/theacodes/nox/issues/412#issuecomment-810164777
- …
=> Add --force-python option as shorthand for --python and --extra-python

docs/usage.rst, nox/_options.py, nox/sessions.py, nox/virtualenv.py, tests/test_main.py, tests/test_sessions.py, tests/test_virtualenv.py
Add option `--no-install` to skip the re-installation of packages when a virtualenv is reused.
Use either of these to reuse a virtualenv without re-installing packages:
```
nox -R
nox --reuse-existing-virtualenvs --no-install
```
The `--no-install` option causes the following session methods to return early:
- `session.install`
- `session.conda_install`
- `session.run_always`
This option has no effect if the virtualenv is not being reused.
Closes #394
Supercedes #411 
Co-authored-by: @jamandbees
=> Add option --no-install to skip install commands in reused environments

nox/manifest.py, tests/resources/noxfile_normalization.py, tests/test_main.py
=> Fix garbled error message when session not found

.isort.cfg, nox/_decorators.py, nox/_version.py, nox/command.py, nox/popen.py, nox/sessions.py, nox/tasks.py, nox/virtualenv.py, noxfile.py, tests/test__option_set.py, tests/test__parametrize.py, tests/test__version.py, tests/test_command.py, tests/test_logger.py, tests/test_main.py, tests/test_manifest.py, tests/test_registry.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_tox_to_nox.py, tests/test_virtualenv.py
Bump the dependencies of Nox's lint session:
- Bump black from 19.3b0 to 21.5b2
- Bump flake8 from 3.7.8 to 3.9.2
- Bump isort from 4.3.21 to 5.8.0
- Bump mypy from 0.720 to 0.812
Fix new warnings and type errors.
Apply changes in code style and import ordering.
Use the new profile feature of isort 5 to achieve compatibility with black.
Supercedes #435
Supercedes #436
Supercedes #437
=> Upgrade linters to the latest version

nox/sessions.py, tests/test__option_set.py, tests/test_manifest.py, tests/test_sessions.py, tests/test_tasks.py
Fixes #400 
Follow-up to #397 
This PR gives each session its own copy of `posargs`, thereby preventing mutations in one session to affect `posargs` in another session. 
```python
import nox
@nox.session
def test(session):
session.posargs.extend(["-x"])
session.install("pytest")
session.run("pytest", *session.posargs)
@nox.session
def lint(session):
args = [*session.posargs, "src"]
session.install("flake8")
session.run("flake8", *args)
```
A test is added to check that `posargs` does not bleed through between sessions. Some existing tests are updated to fix breakage due to the change. There are three groups of tests that broke:
- Tests that compare `posargs` using `is` instead of `==`
- Tests that construct a namespace manually without including `posargs`
- Tests that construct a …
=> Prevent sessions from modifying each other's posargs

CHANGELOG.md, setup.py
What are everybody's thoughts on cutting a release?
- Add option `--no-install` to skip install commands in reused environments. (#432)
- Add option `--force-python` as shorthand for `--python` and `--extra-python`. (#427)
- Do not reuse environments if the interpreter or the environment type has changed. (#418, #425, #428)
- Allow common variations in session names with parameters, such as double quotes instead of single quotes. Session names are considered equal if they produce the same Python AST. (#417, #434)
- Preserve the order of parameters in session names. (#401)
- Allow `@nox.parametrize` to select the session Python. (#413)
- Allow passing `posargs` when scheduling another session via `session.notify`. (#397)
- Add `nox.needs_version` to specify Nox version requirements. (#388) …
=> Release 2021.6.6

tests/resources/noxfile_normalization.py
Fixes #443 
Follow-up to #434 
The test `test_main_with_normalized_session_names` from #434 creates a `.nox` directory under `tests/resources`. This breaks the linting session. Avoid this by passing `venv_backend="none"` to the session decorator.
=> Avoid polluting tests with a .nox directory

nox/virtualenv.py, tests/test_virtualenv.py
=> Fix crash on Python 2 when reusing environments

nox/virtualenv.py, tests/test_virtualenv.py
This PR introduces a feature flag for the staleness check when reusing environments.
The staleness check is deactivated by default. It can be enabled by setting `NOX_ENABLE_STALENESS_CHECK` in the environment. This is an experimental feature, and the environment variable is not a part of Nox's public API. 
See https://github.com/theacodes/nox/issues/449#issuecomment-860030890 for background
=> Hide staleness check behind a feature flag

CHANGELOG.md, setup.py
- Fix crash on Python 2 when reusing environments. (#450)
- Hide staleness check behind a feature flag. (#451)
- Group command-line options in `--help` message by function. (#442)
- Avoid polluting tests with a .nox directory. (#445)
=> Release 2021.6.12

pyproject.toml
This makes the pyproject.toml file available for configuration (such as for #455).
* Gives correct results if wheel is missing (normally a non-wheel build is made, which doesn't pre-cache all pyc files, etc).
* Gives correct results in an environment without setuptools (starting to become more common).
* Is not affected by the current Python environment's installs.
* No effect on legacy pips (pip 9 or less), they work as before.
* Enables using the file for other configuration.
* Likely will become the pip default in the future.
* Can be slightly slower (1-2 seconds) when building from source due to setting up a temporary virtual environment. Besides "correctness is better than speed" for building, this is almost never activated, since this is a pure Python project and has wheels. Users …
=> chore: Use PEP 517 build system

setup.cfg, setup.py
Since this was mentioned in #455 and I happen to have a tool that does 90% of the conversion automatically, here's the setup.cfg conversion. Shouldn't change anything. I left a token setup.py, but it's not even needed anymore even for editable installs on the latest version of pip. You can't remove the file completely though until you have a pyproject.toml file. But once you do, you can remove it if you want.
=> chore: use setup.cfg

docs/index.rst
I've corrected the link to pipx (part of pypa now), as well as added several projects that use nox. Feel free to filter if you want. Current additions:
* pypa/pip
* pypa/cibuildwheel
* pypa/packaging
* pypa/manylinux
* scikit-build (just linked to scikit-build/scikit-build, though scikit-build/cmake uses it too and (eventually) scikit-build/ninja)
* scikit-hep's developer page, which links the scikit-hep projects that use it (scikit-hep/cookie is one of note, along with others)
=> docs: mention more projects that use Nox

nox/tasks.py, tests/test_tasks.py
#462 
Add a friendlier message on the specific case that user is calling
nox from within a directory with no noxfile.
Existing test for this case modified and two additional tests
added to ensure lower level errors are still handled further down.
=> Add friendlier message if no noxfile.py

.github/workflows/ci.yml, noxfile.py
Closes #474 
This PR adds `python 3.10.0-rc2` to `ci.yml` so it will be run as part of the standard CI suite.
I also noticed that the docs action specified python 3.8 but the docs session in `noxfile.py` specified 3.7 causing the docs session to just skip and therefore pass CI without actually building the docs, which I assume is not what we want so I've changed the docs session to python 3.8 in ` noxfile.py` to bring it in line with the other sessions that specify a python.
This is all passing locally and on my forks CI. Let me know if anyone wants anything else as part of this 👍🏻
=> Add python 3.10.0-rc2 to GitHub Actions

nox/sessions.py
Related to some discussion in #398, adds a simple usage  example of `session.notify` to the docs.
=> Add session.notify example to docs

nox/virtualenv.py, tests/test_virtualenv.py
Fixes #345 
First pass at this, I basically just copied the implementation from #371.
=> Conda logs now respect nox.options.verbose.

nox/_decorators.py, nox/_option_set.py, nox/_options.py, nox/_parametrize.py, nox/command.py, nox/manifest.py, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, noxfile.py, tests/resources/noxfile_nested.py, tests/resources/noxfile_pythons.py, tests/resources/noxfile_spaces.py, tests/test_main.py, tests/test_sessions.py
I didn't file an Issue for this one because this is very much down to personal developer preference, so feel free to reject this if you don't want it I won't be offended at all! :)
Things like this would be very tedious to do by hand but I discovered an automated tool [Flynt](https://github.com/ikamensh/flynt) to convert the older style `"{}".format()` strings with newer `f"{}"` style strings and it seems to have worked great!
Since 3.5 is now EOL, it might make sense to convert to the new format!
=> Run Flynt to convert str.format to f-strings

nox/_option_set.py, nox/_options.py, nox/sessions.py, nox/tasks.py, tests/test__option_set.py, tests/test_sessions.py
Closes #469
Added a working directory nox was originaly invoked from to session propreties.
@DiddiLeija I started working on this issue some time ago, but then had a long break and couldn't find time to finalize it until today and now noticed that you already opened a PR for it. Hopefully we did not duplicate much work, sorry for not mentioning it earlier and please let me know if you are ok with me continuing on this one.
=> 469 add initial cwd to session properties

nox/sessions.py, tests/test_sessions.py
Closes #72. Add an `{envdir}/.shared` directory (like @dhermes suggested), and create an API for accesing to it.
I'm a bit new to the concept, so tell me if this is what you want :)
CC @theacodes @cjolowicz
=> Add a "shared cache" directory

.github/workflows/ci.yml, noxfile.py, tests/test__option_set.py
Closes #478 
After some playing around with my fork I've managed to get tests and coverage playing nicely on 3.10.
Summary of changes:
- Detect when we're running on 3.10 and reduce coverage fail under to 99 from 100
- Parametrise `cover` with the same pythons as `tests` so I could access `session.python` to do the above
- Explicitly call `cover-<version`> in the Github Actions workflow (`session.notify` didn't seem to work for me here, I tried both `"cover"` and `"cover-<version>"` as arguments with no luck, if anyone knows how to fix this it would clean this solution up a little bit)
I did also notice that one of the tests (`test_session_completer`) was coupled to the noxfile. I didn't look into it too much but I think we should look at decoupling if possible as then we're free to …
=> CI: Python 3.10.0-rc.2 coverage fix

tests/resources/noxfile_multiple_sessions.py, tests/test__option_set.py
Didn't raise an issue for this because it was discussed here: https://github.com/theacodes/nox/pull/479#issuecomment-920673738
This PR decouples `test_session_completer` from the project's actual noxfile by adding a new fake noxfile with multiple sessions under `tests/resources` and pointing `test_session_completer` at it using the keyword argument.
=> Decouple `test_session_completer` from project level noxfile

nox/sessions.py, tests/test_sessions.py
Closes #481. Create `session.warn` to show warnings during the session.
cc @theacodes @FollowTheProcess
=> Add `session.warn` to output warnings

nox/sessions.py, tests/test_sessions.py
Closes #485. A logging function to show debug-level messages.
=> Add `session.debug` to show debug-level messages

.github/workflows/ci.yml, setup.cfg
This PR changes "3.10.0-rc.2" to "3.10.0" in GitHub Actions now that 3.10 is officially released. I've also added the 3.10 pypi classifier in setup.cfg.
As far as I know conda does not yet support 3.10 so unfortunately we can't combine the testing action just yet!
=> Python 3.10

nox/tasks.py, tests/test_tasks.py
Related to #492.
Currently, providing a `--keywords` argument that is not a valid expression causes Nox to crash with a SyntaxError.
```
$ nox -k 'foo:bar'
Traceback (most recent call last):
...
File "<string>", line 1
foo:bar
^
SyntaxError: invalid syntax
```
This change validates the keywords argument using [ast.parse](https://docs.python.org/3/library/ast.html#ast.parse) and prints an error message if it is not a valid expression.
```
$ nox -k 'foo:bar'
nox > Error while collecting sessions: keywords argument must be a Python expression.
```
=> Show error message when keywords expression contains a syntax error

MANIFEST.in
Closes #504. The removed inclusion was redundant, since we use setuptools>=42.
=> Remove LICENSE from the manifest file

docs/conf.py, noxfile.py
Changes:
- Add Python 3.10 to our `conda_test` session, since GHA already supports Conda (see #501).
- Add `docs/conf.py` to the files where session `lint` will run, to be the same than the `blacken` step (see #499).
=> Improvements to our noxfile

noxfile.py
I was looking through the older issues to try and find the low hanging fruit to close off and found #298.
This PR addresses point 1:
> 1. Change `rm -rf` to [`shutil.rmtree`](https://docs.python.org/3/library/shutil.html#shutil.rmtree).
I did some digging around points 2 and 3, it would seem that point 2 at least has been resolved anyway (see [here](https://github.com/tornadoweb/tornado/issues/2608#issuecomment-736185273)).
> 2. Change the Python version to 3.7 because [sphinx-autobuild](https://github.com/GaretJax/sphinx-autobuild/issues/77), which relies on [tornado](https://github.com/tornadoweb/tornado/issues/2608), no longer works on Windows on 3.8.
Point 3 I'm not too sure and I don't have access to a Windows machine to easily test but since we build the official project docs in an …
=> Use shutil.rmtree over shelling out to rm -rf in noxfile

docs/config.rst, docs/tutorial.rst, docs/usage.rst, nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py
Closes #444.
Initial prototype, no docs or tests yet. Does this look like a good way to do it?
=> feat: add mamba environment

noxfile.py, tests/test_virtualenv.py
Fixes #520
Adds a simple session filter at the top of our `noxfile.py` that runs all sessions (other than `conda_tests`) by default, only adding `conda_tests` if the user has conda installed.
```python
nox.options.sessions = ["tests", "cover", "blacken", "lint", "docs"]
if shutil.which("conda"):
nox.options.sessions.append("conda_tests")
```
I also spotted a stray conda-dependent test without a `pytest.mark.skipif(not HAS_CONDA)` guard on it so I quickly added that too:
```python
@pytest.mark.skipif(not HAS_CONDA, reason="Missing conda command.")
def test_condaenv_(make_conda):
venv, dir_ = make_conda()
assert not venv.is_offline()
```
=> Skip `conda_tests` session by default if user does not have conda

nox/sessions.py, tests/test_sessions.py
Closes #446.
This adds a channel keyword, which can take a string or a list/tuple of channels.
Other options included `channels=`, and only allowing for a sequence of channels, but that probably is optimizing for the less-common case. Simpler API though. Can change if desired.
=> feat: add channel keyword to conda

docs/usage.rst, nox/_options.py
Closes #502.
This is going with `FORCE_COLOR`, following PyPA/build, pytest, & tox. Could be changed.
=> feat: support FORCE_COLOR

.gitignore, .readthedocs.yml, nox/_decorators.py, nox/_parametrize.py, nox/tasks.py, noxfile.py
I've bumped the linting versions to latests, cleaned up the mypy updates, and bumped from Python 3.8 to Python 3.9.
Are you interested in moving to pre-commit + pre-commit.ci, perhaps? That would automate this process of bumping pins and would also help new contributors by automatically running the auto-fixes ("blacken") on PRs if you want it to. I'd apply the method described in https://scikit-hep.org/developer/style and used in pybind11, cibuildwheel, etc.
=> chore: bump linting versions to latest

.github/workflows/ci.yml, noxfile.py
Closes #531 
I've unpinned the `docs` session, leaving `lint` and `blacken` pinned to python 3.9.
I've also added the `--error-on-missing-interpreter` flag to all CI invocations of Nox, to catch any future silent "passes"
=> Unpin docs session and add --error-on-missing-interpreter to CI sessions

requirements-conda-test.txt
Max version of colorlog in `requirements-conda-test.txt` does not support Python > 3.7 making `nox -s conda_tests` fail. The conda_tests session in not run in CI so this is only an issue when running locally.
=> Update dependencies for conda_tests

nox/sessions.py
Closes #517.
This PR added a docstring to explain how `session.run` fails and stop the session. Also, I documented how to handle these failures, like described in #517.
=> Document how `session.run` fails, and how to handle failures 

nox/virtualenv.py, tests/test_virtualenv.py
=> Correct bin paths in CondaEnv for Windows

noxfile.py
Fixes an error in the project's own `noxfile.py` where the `blacken` session was explicitly
listed in `nox.options.sessions` but no longer exists due to being replaced by the pre-commit checks introduced in #530.
Without this fix, just running `nox` will result in the following:
=> Fix project's noxfile sessions definition

nox/virtualenv.py, tests/test_virtualenv.py
=> Fix current Conda env detection

docs/config.rst, nox/sessions.py, tests/test_sessions.py
Close #503.
I've scanned the docs and cannot see anything that should be changed based on this change. Please correct me if I'm wrong.
Also feel free to chime in on the wording of the warning message.
=> Deprecate use of session.install() without a virtual env

docs/config.rst, docs/tutorial.rst, nox/__main__.py, nox/tasks.py, noxfile.py, tests/test_tasks.py
Closes #465.
Setting an empty session list in the noxfile will default to listing the available sessions.
=> feat: support setting an empty session list

.github/workflows/ci.yml, tests/test_main.py
This enables color output on GitHub Actions for Nox itself, as well as pytest and pre-commit, using workflow-wide environment variables. Nox and pytest support `FORCE_COLOR`, while pre-commit supports `PRE_COMMIT_COLOR`.
=> ci: Enable color output from Nox, pytest, and pre-commit

nox/sessions.py, tests/test_sessions.py
Closes #512. Also see the discussion here: #513.
I'm a bit unsure if the changes to the docs are sufficient. Please suggest changes as you see fit.
=> Make Session.chdir() a context manager

noxfile.py
Closes #545 
virtualenv today released [20.11.0](https://github.com/pypa/virtualenv/blob/main/docs/changelog.rst#features---20110) which internally bumps the embedded version of setuptools from 58.3.0 to 59.4.0, which must have contained some breaking change for pre-commit as it depends on [virtualenv>=20.0.8](https://github.com/pre-commit/pre-commit/blob/16f68254a84df8d69431bab2ba410770746b95bd/setup.cfg#L32) so it would have pulled this latest version in
Pinning virtualenv to 20.10.0 inside the lint session has fixed the issue
=> Pin virtualenv version in lint session

tests/test_main.py
I noticed that some tests are now failing on my machine with a `KeyError` because the `FORCE_COLOR` env variable is not set (which is why they don't fail on CI) and we're trying to monkeypatch the value.
This PR adds a quick check to see if it's set first before monkeypatching the value for tests 👍🏻
=> Fix local test failure to do with FORCE_COLOR

.github/workflows/ci.yml, noxfile.py
Related to discussion in #547.
Related explanation: https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763
Turns out a better solution to pinning virtualenv is enforcing the stdlib setuptools in CI through an environment variable, which this PR implements
=> Fix virtualenv setuptools

nox/_options.py, nox/sessions.py
Closes #546, followup to #448. Mamba should be mentioned in listings of backends.
=> fix: include mention of mamba in more places

.pre-commit-config.yaml, MANIFEST.in, noxfile.py, pyproject.toml
Adds a manual check for the manifest (runs when running `nox -s lint`, but won't auto-run on `pre-commit install` or on `pre-commit.ci`, because it's kind of slow).
This adds the missing tests folder to the SDist. Some users (especially packagers like conda-forge and linux distros) like having it in the SDist.
See #550.
=> style: check manifest

nox/sessions.py, tests/test_sessions.py
This is a minimal fix to the bug, though maybe `create_tmp` should also be absolute? That's less important, because someone could construct the correct path, while TMPDIR simply breaks.
Closes #555
=> fix: support changing directory with TMPDIR

docs/conf.py, requirements-test.txt
Closes #559 again.
See https://github.com/readthedocs/recommonmark/issues/221 - recommonmark has been sun-setted, myst-parser is the replacement.
=> docs: use myst-parser for md

.pre-commit-config.yaml, nox/_options.py, nox/command.py, nox/popen.py, nox/sessions.py, nox/tasks.py, nox/virtualenv.py, tests/test_sessions.py
Closes #568 
Added bonus is black is now 22.1.0 and the `--preview` flag sorts out long strings automagically!
Only other code change was a `# type: ignore` removal
Edit: I think my VSCode has some yaml formatting coming from somewhere, it seems to have increased the indentation of the whole file making the changeset look bigger than it actually is!
=> Bump pre-commit linter versions to latest

docs/usage.rst, nox/_option_set.py, nox/_options.py, nox/sessions.py, tests/test_sessions.py
Closes #340 
This PR adds a check to determine if nox is running on CI when evaluating sessions with missing interpreters so that such sessions fail by default when being run on CI providers.
This has the desired effect:
**Skipped locally showing CI warning**
**CI=true causes an error**
*Note non-zero exit code*
**`--error-on-missing-interpreters` for reference**
I have some questions I'd like people's input on:
- Should this be documented or just rely on the warning message?
- The warning message is kinda long, any other suggestions that get the point across? Maybe just say it will fail in CI and leave it there without mentioning `--error-on-missing-interpreters`? Given that it will show any time a session is skipped a long message could get annoying.
- Currently we just check for `CI` …
=> Missing interpreters now error the session on CI by default

nox/tasks.py, tests/test_tasks.py
Closes #566 
This PR fixes the incorrect raising of `FileNotFoundError` when loading the nox module if it contains module-level file operations on non-existing files.
I've moved the `_load_and_exec_nox_module` past the `FileNotFoundError` and `OSError` exception checks and changed the exceptions it could raise into assert statements as they were all covering internal importlib exceptions that are pretty much fatal.
See conversation on issue from this comment onwards for context: https://github.com/theacodes/nox/issues/566#issuecomment-1029360408
=> Fix incorrect FileNotFoundError in load_nox_module

nox/tox_to_nox.jinja2, nox/tox_to_nox.py, tests/test_tox_to_nox.py
Closes #573. Introduces a function which translates dashes to underscores in tox env names and prints a warning if any other non-identifier character is seen in a tox env name.
=> tox-to-nox: handle non-identifier env names

nox/tox_to_nox.jinja2, tests/test_tox_to_nox.py
Closes #574. I didn't see any tox-to-nox tests, but it's a small enough change to manually confirm.
=> tox-to-nox: support descriptions

nox/_options.py, nox/popen.py, nox/sessions.py, tests/test_sessions.py
Thank you  for the work done in https://github.com/theacodes/nox/pull/393! It did fix some odd issues but brought to light one more. We have a few tests that spin up docker containers and then clean them up after the pytest session exits but these take upwards of 10-15 seconds to fully clean up. I think that making the timeout configurable may be acceptable although I'm not sure if this is the best approach. Let me know what you think.
The goal of this change is to allow you to set the timeout on the CLI, in the `noxfile.py`, or individually on each `session.run` invocation. If this is acceptable I'll work on updating docs and tests. Thanks!
=> feat: allow configurable child shutdown timeouts

CHANGELOG.md, CONTRIBUTING.md, docs/conf.py, docs/cookbook.rst, docs/tutorial.rst, docs/usage.rst, nox/__main__.py, nox/_option_set.py, nox/_options.py, nox/_parametrize.py, nox/_version.py, nox/manifest.py, nox/py.typed, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, tests/resources/noxfile_multiple_sessions.py, tests/test_logger.py, tests/test_main.py, tests/test_tasks.py, tests/test_tox_to_nox.py
Closes #579
This PR aims to fix the inconsistent spelling of `Nox` and `Noxfile` all while leaving the `nox` executables and `noxfile.py` files unchanged.
=> Added consistent spelling

pyproject.toml, requirements-dev.txt
Closes #570 (Following https://github.com/theacodes/nox/issues/570#issuecomment-1033141676).
This requirements file will:
- Perform an editable install of Nox.
- Install both the regular and conda requirements.
@cjolowicz @FollowTheProcess
=> Create a `requirements-dev.txt`

docs/tutorial.rst
This line should be `session.install("pytest")` from the context.
=> Fix typo in tutorial.rst

CONTRIBUTING.md, README.rst, docs/conf.py, docs/index.rst, setup.cfg
Since we have moved to Winterbloom (hooray! :tada:), the current classifiers and links are now outdated. This PR intends to solve this situation.
When this PR gets ready, please let me know if I missed something.
=> Update the classifiers, documentation, and more to point to the new Winterbloom location

.pre-commit-config.yaml
This fixes an issue with a breaking Click update.
See https://github.com/psf/black/issues/2964 for full details.
=> Bump pre-commit deps, to fix a breaking Click update

docs/cookbook.rst
This adds a `VENV_DIR` constant to the example `dev` session in the cookbook as described in #588
=> Add VENV_DIR to `dev` session in cookbook, fix #588

noxfile.py
This PR drops the flag in our Noxfile that would set the `fail_under` threshold to 99% on python 3.10. This was a hangover from when we were testing against 3.10.0-rc.2 in GHA and coverage was raising a few false positives.
Judging by recent runs this flag can be removed now.
See this comment for further details: https://github.com/wntrblm/nox/pull/592#issuecomment-1091830649
=> Drop 99% coverage threshold flag for 3.10 in noxfile

nox/sessions.py
This PR adds generic type arguments to type hints in `sessions.py`, I did not have time to go through the whole codebase unfortunately.
The benefit of adding type arguments is that type checkers like [Pyright](https://github.com/microsoft/pyright) will complain if you access a variable that has a potentially unknown type, for example I ran into this:
```py
import nox
@nox.session(reuse_venv=True)
def pyright(session: nox.Session) -> None:
session.env['ENV_VARIABLE'] = '1'
```
If you want to avoid errors like these in the future, I'd highly recommend adding pyright to CI and using [--verifytypes](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#verifying-type-completeness).
=> Add some missing generic type arguments

.pre-commit-config.yaml, nox/_decorators.py, nox/_option_set.py, nox/_options.py, nox/_version.py, nox/command.py, nox/logger.py, nox/manifest.py, nox/popen.py, nox/sessions.py, nox/virtualenv.py, nox/workflow.py, pyproject.toml
This is a followup to (and includes) #595. Enabling full strictness checking for mypy and bumping the version of mypy (which removes a few ignores).
There are still two sets of ignores that can likely go away in the future. There are some around py.path that will go away with #592. There are also likely some related to function decorators - by properly typing decorators with generics, we can tighten that up and make those work better too (but that's a followup for some other time).
Closes #595 if this gets merged before that, since it contains that commit.
- Add some missing generic arguments
- fix(types): add full strict checking
- fix(types): enable extra error checks
=> fix(types): full strictness checking on mypy

.github/ISSUE_TEMPLATE/config.yml
This is the follow-up of #600, as we discussed in #534. This will add a link to the Winterbloom Discord (to be more precise, the link shared in https://github.com/wntrblm/nox/issues/534#issuecomment-1111552113).
=> Create the `config.yml` file for issue templates

.github/ISSUE_TEMPLATE/config.yml
This PR fixes the Nox channel name in the `config.yml` which, as it's preceeded by a '#', yaml assumes it's a comment and does not display everything after it:
=> Fix discord channel name in config.yml

.pre-commit-config.yaml
As of version 3.0, Jinja2 includes type hints. These should be preferred to the (no longer updated) stub package from typeshed.
=> Prefer type checking against Jinja2

README.md
This PR changes the syntax for the alice logo in the README from a hardcoded relative path to a static GitHub link so that it will render properly on e.g. PyPI
=> docs: Use link for README logo

.github/workflows/ci.yml, noxfile.py, pyproject.toml
This PR does a few little chore type items:
* Type check the `noxfile.py`
* I attempted to remove the seemingly unnecessary `session.create_tmp()` call in the test sessions but this then failed on Windows with the classic Errno13 Permissions so I put them back with an explanatory comment to warn future meddlers
* Format the `pyproject.toml` using the [even better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) VSCode extension (This was mostly by accident but it looks nice)
* Remove the `SETUPTOOLS_USE_DISTUTILS` switches mentioned in #545 as the underlying issue is now fixed
=> chore: Few tidy ups

.github/dependabot.yml, .github/workflows/ci.yml
This PR updates both `actions/checkout` and `actions/setup-python` to the latest major version (v3), and adds a GitHub built in dependabot config to ensure they are kept up to date.
Also changed `pypa/gh-action-pypi-publish@master` to `pypa/gh-action-pypi-publish@v1.5.0` as a best practice type thing, incase the master branch ever breaks, also allows dependabot to chip in with this one too 🙂
=> ci: Update GitHub actions to latest and add dependabot

.github/workflows/ci.yml, tests/test_virtualenv.py
This PR bumps the GHA runners to the `-latest` versions. The versions can be found on the GitHub actions docs [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) but a brief summary of the changes is:
* **Ubuntu:** No change, `latest` uses `20.04` already
* **Windows:** Windows 2019 to Windows 2022
* **macOS:** New runner, `macos-latest` uses macOS Big Sur 11
There was a new failing test on Windows python3.7 testing the reuse of a python2.7 environment failing with an `io on closed file` error, I've simply skipped it if on Windows as it's passing everywhere else and ofc python2.7 is deprecated
=> ci: Use latest GHA runners and include macOS

.pre-commit-config.yaml, pyproject.toml
Now we have a PEP 621 pyproject.toml I was looking around for an equivalent to the excellent [setup-cfg-fmt](https://github.com/asottile/setup-cfg-fmt) and found [pyproject-fmt](https://github.com/tox-dev/pyproject-fmt) which seems to do a similar set of things, i.e. not only formatting but sorting keys and cleaning up certain things.
I figured since we were formatting `setup.cfg` in pre-commit runs we should do the same with `pyproject.toml` 👍🏻
=> chore: Apply consistent format to pyproject.toml

pyproject.toml
I've discovered (by accident) something quite unfortunate about the PEP 621 pyproject.toml `license` field. I recently ported [pytoil](https://github.com/FollowTheProcess/pytoil) to support PEP 621 and released a new version with the following config:
```toml
license = {file = "LICENSE"}
```
However this gives a rather ugly representation of the entire file on PyPI:
This can be fixed by simply passing the name of the license in the `text` key like so:
```toml
license = {text = "Apache-2.0"}
```
Which results in what you'd expect:
And I can confirm that the full LICENSE file is still included when running `pyproject-build`:
=> fix: PEP 621 license field

docs/conf.py
Warnings are treated as errors so this is currently failing CI builds of docs.
=> fix(docs): Configure language code to avoid warning on sphinx build

.github/action_helper.py, .github/workflows/action.yml, .pre-commit-config.yaml, action.yml, docs/tutorial.rst, noxfile.py, tests/test_action_helper.py
This is another way to implement the feature discussed in #601.
It hopefully addresses any shortcomings in the implementation except for the yaml list which is still not possible but has been replaced with a simple enough comma-separated list.
It now supports any python version supported by `actions/setup-python@v3` with up-to 20 versions installed.
The python validation/helper script which is currently inlined in the action might benefit from being a standalone script allowing for proper testing. I can do this if maintainers want to pursue this further.
One thing discovered while working on this is that mixing `actions/setup-python` & `wntrblm/nox` actions might not be that safe.
e.g. let's say that for some reason that I need `pypy-3.9-nightly` because of a bug in `pypy-3.9`:
```
- …
```
=> feat: allow defining a python version list for GHA action (alt)

docs/config.rst, docs/tutorial.rst, docs/usage.rst, nox/_decorators.py, nox/_options.py, nox/manifest.py, nox/registry.py, nox/sessions.py, nox/tasks.py, tests/test_manifest.py, tests/test_registry.py, tests/test_tasks.py
=> feat: Add session tags

action.yml
This removes the dependence on the final output being reasonable to run nox. Targeting only <3.7 is valid now.
CC @mayeut
=> fix: use setup-python v4.1's environmentless setup

action.yml
GHA does not error out on invalid input name but instead only shows a warning which is why this did go unnoticed.
=> fix: invalid input in action's localpython step

.github/action_helper.py, .pre-commit-config.yaml
With #629 merged in, `action_helper.py` can now use python 3.7+ syntax and undergo the same pre-commit checks as the rest of the code base.
=> chore: use python 3.7+ syntax for action_helper.py

nox/sessions.py, tests/test_sessions.py
Closes #636. The environment variable `NOX_CURRENT_SESSION` is populated with the name of the current session in all subcommands of that session. 
There were a couple places to place this small bit of code. Each location caused some problems with the existing tests. The current place was chosen because it intuitively makes sense to take code that the user would write at the top of their session functions and move it up into the thing that calls the session function. Let me know if you think it belongs elsewhere.
=> Export session name in envvar NOX_CURRENT_SESSION

nox/_option_set.py, nox/_options.py
=> Add short -N alias for --no-reuse-existing-virtualenvs

.pre-commit-config.yaml, MANIFEST.in
Closes #644 
Added `.github/action_helper.py` to manifest file.
I unpacked the tarball generated by [pypa/build](https://github.com/pypa/build) and you can see that it gets correctly included:
=> fix: Include action helper in MANIFEST.in

.pre-commit-config.yaml, nox/_option_set.py, nox/_typing.py, nox/_version.py, nox/manifest.py, nox/sessions.py, tests/test__parametrize.py
I noticed while working on #645 that the pre-commit hooks were a bit out of date and didn't want to clutter that PR with these changes.
This PR updates all the pre-commit hooks and makes any new suggested changes to pass the lint suite 👍🏻
=> chore: Update pre-commit hooks and fix any resulting errors

nox/sessions.py
I found this extremely useful feature only by accident and Googling!
Not sure if y'all enjoy retroactive changelog editing…
=> Add docs for #180

nox/command.py, tests/test_command.py
Everything previously really worked fine in theory, but the debug string
which is logged (and calls shlex.quote) was blowing up trying
to quote a pathlib.Path object. I'm somewhat surprised upstream
shlex.quote doesn't support pathlib.Path objects (yet?) but for
now this just falls back to a cruder representation.
(Obviously there are other ways to handle this, like calling str() on all the args, let me know if you prefer something else).
This also apparently doesn't work on Windows, but that's because `subprocess.Popen` is apparently broken with WindowsPaths. The upstream bug is  https://github.com/python/cpython/issues/85815.
=> fix: nox.session.run-ing commands with pathlib.Path arguments

docs/tutorial.rst
Current example feeds `session.posargs` directly into `session.run`. I don't _think_ this works—as `session.posargs` is a list. Added an unpacking argument `*` as a quick fix.
---
Thanks for the great work here!
=> Fix example in docs using `session.posargs`

.pre-commit-config.yaml, nox/command.py, nox/sessions.py, nox/virtualenv.py, pyproject.toml, tests/test_command.py, tests/test_virtualenv.py
closes #583 
I picked up @henryiii's excellent work on #592, resolved the conflicts and the issue he described with `shutil.which` expecting a `.exe`.
This should hopefully be everything needed to drop `py.path`, @henryiii I'd be grateful if you could check this out to see if I've solved the issue adequately as you have more of the context than me 🙂
=> refactor: Drop `py` as a dependency

.pre-commit-config.yaml, nox/sessions.py, tests/test_command.py
Some pre-commit updates, including a spelling fix & some new formatting from the "future" black setting.
=> chore(deps): update pre-commit

nox/_decorators.py, nox/_option_set.py, nox/_options.py, nox/_parametrize.py, nox/_typing.py, nox/logger.py, nox/sessions.py, nox/virtualenv.py, pyproject.toml
I tried running `refurb`, and it had a few good suggestions, I also found some old Python workarounds (for 3.6.1 and before) that could be cleaned up.
=> chore: some refurb suggestions and cleanup old Python 2-3.6 stuff

docs/tutorial.rst
Currently example for GitHub actions will not run, and needs a version tag. Defaulted to using `@latest`.
(At least partially) closes #643
---
Thanks for all the work here. Really enjoy using nox.
=> Make GitHub Actions `uses` example runnable

docs/tutorial.rst
Fixes a mention in the docs to `@latest` which doesn't actually refer to a valid tag, my bad for not spotting! 👍🏻 Thanks @henryiii
=> Point action docs to 2022.8.7 not latest

.github/action_helper.py, .github/workflows/action.yml, .github/workflows/ci.yml, action.yml, docs/tutorial.rst, docs/usage.rst, tests/test_action_helper.py, tests/test_main.py
This moves to using Python 3.11 final on GHA as well as uses it by default for the action.
While doing this, I noticed we are using the deprecated set-output string. I'll try to make a followup that fixes this.
=> chore: move to 3.11 final

.github/action_helper.py, .github/workflows/action.yml, action.yml, tests/test_action_helper.py
The `set-output` workflow command [has been deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) and replaced with writing to an environment file. Update `.github/action_helper.py` to use the new file.
=> Action: Replace deprecated set-output command

.github/workflows/action.yml, noxfile.py
I noticed that on the recent release, the `action_default_tests` were failing asserting that the calling python was 3.10 when in fact it was 3.11 due to #667 
This PR updates the assertion to 3.11
=> Fix assertion in GHA tests

.github/workflows/ci.yml
Fixes to get CI working again, and some speed improvements.
=> ci: some minor fixes

.flake8, .github/workflows/ci.yml, pyproject.toml, requirements-conda-test.txt, tests/test_virtualenv.py
- Constrain to tox<4.0.0 until #673 is addressed
- Use recommended pypa/publish version syntax
- Ignore B905 warning which is only specific to 3.10+
- Remove an unused rogue mock of `py._path`
=> Constrain tox to <4.0.0 and minor fixes

.flake8
This is a better fix for the opinionated checks for bugbear. Since they may be added supporting newer than EoL Pythons, it’s best to just activate the known safe ones. Otherwise this might have to be fixed every release that adds a new opinionated check.
=> chore: long term fix for bugbear opinionated checks

.pre-commit-config.yaml, docs/conf.py, docs/usage.rst, nox/_options.py, requirements-test.txt, tests/test_main.py
=> Add support for `NOXPYTHON`, `NOXEXTRAPYTHON` and `NOXFORCEPYTHON`

.flake8, .pre-commit-config.yaml, nox/_parametrize.py, nox/command.py, nox/manifest.py, nox/virtualenv.py, pyproject.toml, tests/test_command.py, tests/test_manifest.py, tests/test_tasks.py
Ruff can take the place of a lot of other tools, and is 10-100x faster (written in Rust), plugins can't get out of sync, zero dependencies, can auto-fix in some cases, pyproject.toml configuration, and poetry-core updates can't break it (like isort). :)
cibuildwheel, build, scipy, and others have already moved to it.
There are some other nice codes we could enable, but stuck with either what was there before or easy-to-enable (minimal changes) ones.
=> chore: move to using Ruff

docs/usage.rst, nox/_options.py, nox/tasks.py, tests/test_tasks.py
Closes https://github.com/wntrblm/nox/issues/658.
No tests yet. Putting out an initial design.
Here's the output on nox itself:
```bash
nox --json -l -s cover lint | jq
```
```json
[
{
"session": "cover",
"name": "cover",
"description": "Coverage analysis.",
"python": null,
"tags": [],
"call_spec": {}
},
{
"session": "lint",
"name": "lint",
"description": "Run pre-commit linting.",
"python": "3.9",
"tags": [],
"call_spec": {}
}
]
```
And it can be processed by jq:
```console
$ nox --json -l -s tests | jq '.[].session'
"tests-3.7"
"tests-3.8"
"tests-3.9"
"tests-3.10"
"tests-3.11"
```
Thoughts?
=> feat: --json --list-sessions

nox/_version.py, tests/test_virtualenv.py
fixes #701 
Newer virtualenv versions have dropped py2.7 support.
=> Don't run python 2.7 virtualenv tests for newer versions of virtualenv

nox/_options.py
Otherwise we end up erroring out due to no session being selected (which in turn errors out due to global color setting not finalized/available at this phase yet.)
```shellsession
$ eval -- "$(register-python-argcomplete nox)"
$ export _ARC_DEBUG=1
$ nox -s <TAB>
[...]
File ".../nox/nox/_options.py", line 234, in _session_completer
filtered_manifest = filter_manifest(manifest, global_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File ".../nox/nox/tasks.py", line 185, in filter_manifest
_produce_listing(manifest, global_config)
File ".../nox/nox/tasks.py", line 235, in _produce_listing
reset = parse_colors("reset") if global_config.color else ""
^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'color'. Did you mean: 'nocolor'?
[...]
```
=> fix: enable `list_sessions` for session completion

README.md
Projects such as black, isort, Ruff, and Hatch have official badges that they provide to users to allow them to promote their projects to great affect.
[![Code style: black][black-badge]](https://github.com/psf/black) [![Imports: isort][isort-badge]](https://pycqa.github.io/isort/) [![Ruff](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/charliermarsh/ruff/main/assets/badge/v1.json)](https://github.com/charliermarsh/ruff) ![Hatch project](https://img.shields.io/badge/%F0%9F%A5%9A-Hatch-4051b5.svg)
[black-badge]: https://img.shields.io/badge/code%20style-black-000000.svg
[isort-badge]: https://img.shields.io/badge/%20imports-isort-%231674b1?style=flat&labelColor=ef8336
This adds a new badge for Nox inspired by [Alice's dress in the …
=> Create an official Nox badge

docs/tutorial.rst
Follow on to #714 
Document to users how they can embed the official Nox badge.
Content inspired by the badge section of Hatch's user guide: https://hatch.pypa.io/latest/next-steps/#community
=> Document how users can embed the official Nox badge

nox/command.py, nox/sessions.py, tests/test_command.py, tests/test_sessions.py
Closes #253 
Introduced a new parameter `include_invocation_env_vars` to the `session.run` related methods. It can be a boolean or an iterable of vars that should be included from the nox invocation environment. Some env vars (inspired by [tox](https://tox.wiki/en/latest/config.html#conf-passenv) are always passed in to ensure proper functionality of stdlib functions and pip.
=> Enhance environment variables passing

nox/_options.py, tests/test_tasks.py
=> Merge sessions and tags

nox/_options.py
Issue: https://github.com/wntrblm/nox/issues/708
`Tests passing. Ideally, I think --force-color should override NO_COLOR in the containing environment rather than collide with it.`
With this modification, if `--force-color` is provided, it will return `True` and **enforce colors**, even if `NO_COLOR` is set in the environment. If `--no-color` is provided or `NO_COLOR` is set in the environment, it will return `False` and **disable** colors unless `--force-color` is also provided.
=> Change _color_finalizer behavior

docs/cookbook.rst
If you use parametrized tests they will include single quotes, breaking the output 😊
=> Use double quotes instead of single in github actions examples

tests/test_tox_to_nox.py, tests/test_virtualenv.py
Noticed these when running locally. I think `tox_to_nox` was forcing an old version of `virtualenv` that still had `version.version` - current versions do not. Made the simplest change - a safer long term fix would probably be to use `importlib.metadata.version` instead of depending on something inside the package.
=> tests: fixes when running locally

.github/action_helper.py, .github/workflows/action.yml, action.yml, docs/tutorial.rst, noxfile.py, tests/test_action_helper.py
The nox action can be simplified now that setup-python allows to setup multiple interpreters natively.
This also adds support for `~` version specifier (e.g. `~3.12.0-0`) which mostly should not be necessary as setup-python now supports `allow-prereleases` which transforms `3.12` into `~3.12.0-0` when searching for CPython 3.12.
The `~` specifier might be interesting for those who want a minimum patch version, e.g. `~3.11.1` <=> `>=3.11.1 <3.12`.
=> action: use multiple interpreters features from 'actions/setup-python@v4'

nox/_option_set.py, nox/_options.py, tests/resources/noxfile_options.py, tests/test_main.py
Minor follow up to changes introduced by #567 which caused the regression issue for #650 
This PR fixes an issue with the new `default` option in `make_flag_pair` introduced in #567 that caused values set in the `noxfile.py` to be ignored when set to `False` if the default is `True` due to the evaluation done in `flag_pair_merge_func`.
This PR also changes the `default` kwarg option in `make_flag_pair` introduced in #567 to allow callables for ease of testing and therefore switches the default of `error_on_missing_interpreters` to `default=lambda: "CI" in os.environ`. End result should be the same as before.
Also added a test for this to be a bit more thorough with this particular issue of default is `True`, but noxfile is `False`.
=> Allow override via noxfile of nox.options.error_on_missing_interpreters

nox/_decorators.py, nox/_option_set.py, nox/_parametrize.py, nox/command.py, nox/manifest.py, nox/popen.py, nox/registry.py, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, nox/workflow.py, tests/test__parametrize.py, tests/test_manifest.py
This fixes an issue with `os.PathLike[str]` being accepted but not present in the typing. It also uses `collections.abc` wherever possible instead of `typing` (can't fully change all of them until 3.9+ is supported, due to runtime requirements). It also uses `Sequence`/`Mapping`/`Iterable` for input parameters (you should be generic in input, specific in output) - doing so adds a few copy functions and improves safely a bit, fewer arguments are allowed to be mutated later this way). A few `TypeVars` were added - they can be replaced with native syntax in Python 3.12+.
Noticed in https://github.com/scikit-build/scikit-build-core/pull/408 where mypy found two real problems in my noxfile, and one false positive, which this fixes.
=> fix(types): improve typing

.github/workflows/action.yml
Removed the problematic Python 2.7.18 version, since Python 2.7 is no longer supported and the specific version 2.7.18 was not found.
I removed it from the python-versions list.
Reference: https://github.com/actions/setup-python/issues/672
=> Removed the problematic Python 2.7.18 version

nox/__main__.py, nox/_decorators.py, nox/command.py, nox/registry.py, nox/tox_to_nox.py, nox/workflow.py
Hi there,
I've made some minor updates to the project and submitted them in this pull request. The changes I've made include:
1. Creating a separate function called "execute_workflow" to handle the execution functionality.
2. Including more type hints to make the code clearer.
3. Adding docstrings to provide better documentation.
This is my first pull request to improve the codebase's style, but I plan to make more soon. Please take a look and let me know if you have any feedback.
Thank you!
=> style: add type hints, update few functions

.github/workflows/ci.yml, action.yml, noxfile.py
Add Python 3.12 to our supported pythons, as 3.12 is now stable, in both the CI checks and our Github action.
Closes #742.
=> Include Python 3.12 in GHA

.pre-commit-config.yaml, docs/usage.rst, nox/_option_set.py, nox/_options.py, nox/registry.py, noxfile.py, pyproject.toml, tests/test__version.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_tox_to_nox.py, tests/test_virtualenv.py
Update Ruff to modern lint-prefixed structure and update pre-commit hooks.
=> chore: modernize Ruff config, bump pre-commit

.pre-commit-config.yaml, nox/_option_set.py, nox/registry.py, pyproject.toml, tests/test__version.py, tests/test_action_helper.py, tests/test_tasks.py, tests/test_tox_to_nox.py
I did this in two steps, to illustrate that ruff-format matched black in non-preview style.
See https://github.com/wntrblm/nox/pull/736. Also https://github.com/scientific-python/cookie/pull/299, which I've been mentioning whenever I make a PR moving to ruff-format.
- style: remove --preview from black
- chore: move to ruff-format
=> chore: ruff-format

.github/workflows/action.yml, action.yml, noxfile.py
Update default python-versions to non-EOL pythons.
=> chore(action): update default python-versions

.github/workflows/action.yml, .github/workflows/ci.yml
This is useful to run workflows on branches in forks before a PR is opened here.
=> chore(ci): allow manual runs on branches without a PR

pyproject.toml, requirements-conda-test.txt
`virtualenv` dependencies, for example
- https://github.com/pypa/virtualenv/issues/2666
can cause dependency resolution of `virtualenv` to drop to an older version (for example `20.4.7`) that can cause `nox` to fail due to using deprecated `setuptools` behavior. For example:
- https://github.com/johnthagen/python-blueprint/actions/runs/6834646086/job/18587635299
Bump nox's minimum `virtualenv` version to avoid dependency resolution selecting a very outdated `virtualenv`, which isn't tested and can fail.
[virtualenv 20.14.1](https://virtualenv.pypa.io/en/latest/changelog.html#v20-14-1-2022-04-11) was released 2022-04-11.
=> Bump minimum virtualenv to 20.14.1

nox/_options.py, nox/manifest.py, tests/test_manifest.py
Also adds the shorthand `-P` for the `--force-python` option.
Closes #623
=> Allow `--force-python` on unparametrized sessions

nox/_option_set.py, nox/_options.py, tests/resources/noxfile_pythons.py, tests/resources/noxfile_tags.py, tests/test__option_set.py
See individual commits for details.
=> feat: more option argument completions

.github/workflows/ci.yml, nox/tox4_to_nox.jinja2, nox/tox_to_nox.py, noxfile.py, pyproject.toml, tests/test_tox_to_nox.py
Fixes: #673 
It seems to me that the easiest way forward is to call `tox config`, parse the output and then preprocess it into a dictionary so it can be easily used in the jinja template.
What do you think?
From this tox.ini:
```
[tox]
envlist = black,mypy,py{36,37,38,39,310,311,312}
isolated_build = True
[testenv]
commands =
python -m platform
pytest -v {posargs} test.py
deps =
pytest
[testenv:black]
description="better than blue"
skip_install=true
deps=black
commands=black --check --diff --extend-exclude=".tox|test" ./
[testenv:mypy]
use_develop=true
deps=mypy
commands=mypy --strict -p marshalparser
```
it now generates this noxfile.py
```python
import nox
@nox.session()
def DEFAULT(session):
""""""
session.install('.')
@nox.session(python='/home/lbalhar/.virtualenvs/nox/bin/python') …
```
=> First implementation of tox_to_nox for tox 4

tests/test_virtualenv.py
I can't run the tests locally and see coverage because it fails on one test - if you have `py` (the Python launcher for UNIX) installed, it breaks the assumptions of this test. Fixed and used print instead of noqa to make it easier to debug in the future.
=> tests: support running when the Python launcher for UNIX is present

README.md, docs/index.rst
This adds some links, updates a few more projects, and adds me too. Also updates the install suggestion based on the README suggestion.
=> docs: update some links

.github/workflows/ci.yml, nox/_version.py, nox/command.py, nox/logger.py, noxfile.py, pyproject.toml, requirements-test.txt
Different OS's are producing the same files currently. Noticed in #762. I think this might be why #772 is failing, too.
=> ci: fix coverage combine for different OS's

docs/usage.rst, nox/_options.py, nox/sessions.py, nox/virtualenv.py, pyproject.toml, requirements-test.txt, tests/test_sessions.py, tests/test_virtualenv.py
UV just came out from the Ruff folks, and it's insanely fast - it makes venvs faster (25ms) than Python can start up (50ms). And much faster than virtualenv (400ms) and venv (nearly 5 seconds). The package install speeds are also unreal compared to pip.
There are some differences - namely `name @ .` is [required](https://github.com/astral-sh/uv/issues/1499) instead of `.` if an install is not editable (for now). But it's really nice to try it out!
https://github.com/wntrblm/nox/assets/4616906/1fe4c981-9d9a-4aaf-b19e-94c79daeebe7
Nox's docs build in 4 seconds instead of 22 seconds using the uv backend.
=> feat: add a uv backend

docs/conf.py, nox/_option_set.py, nox/_options.py, nox/_parametrize.py, nox/_version.py, nox/logger.py, nox/sessions.py, pyproject.toml, tests/test_main.py
Just a few minor cleanups. Ruff doesn't need the target version if you use PEP 621 metadata. Added the pylint checks (minus a few). Did just a bit of cleanup.
=> chore: cleanup Ruff a bit

docs/config.rst, docs/usage.rst, nox/_options.py, nox/sessions.py, tests/conftest.py, tests/resources/noxfile_options.py, tests/test_main.py, tests/test_sessions.py, tests/test_tasks.py
Closes #488
This PR introduces a new option `reuse_venv` at the CLI and nox.options level as discussed in #488. It takes 4 possible values, namely `no`, `yes`, `never`, and `always` as discussed in the issue.
The code that evaluates if a venv should be reused has been switched to use this new option, and backwards compatiblity with `reuse_existing_virtualenvs` is kept using appropriate `finalizer_func` and `merge_func` on `_options.py`.
I've added tests to test new functionality as well do backwards compatibility checks and hopefully 🤞 updated the docs properly. I also added a new fixture `generate_noxfile_options` that helps with more dynamic configuration of `resources/noxfile_options.py` used in the tests to reduce boilerplate.
=> feat: support for reuse_venv option

docs/usage.rst, nox/_options.py, tests/test_main.py
Closes https://github.com/wntrblm/nox/issues/776
=> feat: Allow configuring default backend with an environment variable

nox/virtualenv.py, tests/test_virtualenv.py
This is a followup to #762. Switching environments is likely to be a bit more common, so let's handle it correctly. This has a key path comparison fix that I think was stopping this from being the default before, and instead available via a secret environment variable used in tests.
This is also now "smart" about switching between compatible backends. Switching from venv to virtualenv or back won't trigger a rebuild.
@slafs, could you check this?
=> fix: rebuild env if making an incompatible change

nox/sessions.py, tests/test_sessions.py
They probably meant to unpack the list.
Closes https://github.com/wntrblm/nox/issues/746
=> fix: warn user when first argument to session.run is a list

nox/_options.py
Quick fix for the missing f-string in the `--help` message for `-db` and `-fb`:
```
-db {conda,mamba,virtualenv,venv,uv,none}, --default-venv-backend {conda,mamba,virtualenv,venv,uv,none}
Virtual environment backend to use by default for Nox sessions, this is ``'virtualenv'`` by default but any of ``{list(ALL_VENVS)!r}`` are accepted.
-fb {conda,mamba,virtualenv,venv,uv,none}, --force-venv-backend {conda,mamba,virtualenv,venv,uv,none}
Virtual environment backend to force-use for all Nox sessions in this run, overriding any other venv backend declared in the Noxfile and ignoring the default backend. Any of ``{list(ALL_VENVS)!r}`` are accepted.
```
In the long run, it would be nice to clean the `--help` message up some more. Like those quotes with double backtick and single quote, and the …
=> fix: missing f-string in --help message

tests/test_sessions.py
=> tests: skip test for conda env when conda isn't installed

docs/config.rst, docs/usage.rst, nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py, tests/test_virtualenv.py
The venv property is also called `venv_backend` (matching the original property on the Venv subclass).
Closes #796.
=> feat: add venv_backend property

.pre-commit-config.yaml, nox/sessions.py, nox/virtualenv.py, pyproject.toml, tests/test_sessions.py, tests/test_virtualenv.py
=> fix: look for uv next to python if it's not on PATH

.github/workflows/action.yml, action.yml, noxfile.py
pipx is being re-added in https://github.com/actions/runner-images/pull/9474
blocked by https://github.com/actions/runner-images/issues/9256 (`temp: don't use pipx` commit)
blocked by https://github.com/actions/setup-python/issues/808 (`temp: python 3.8 & 3.9 missing on macos-14` commit)
=> feat(action): do not depend on pipx in Nox action

nox/virtualenv.py, tests/test_virtualenv.py
Fix #801.
Needs a test were we manually set one variable and make sure it isn't present. It might be the parent `run` overrides it.
I'd like to allow this at the user level, too; setting `env={"UNSET_ME": None}` would be a good way to provide an "unset" list. You can set to an empty string, but that's not always the same as not having the variable in the first place.
=> fix: avoid mixing venv and conda from environment

nox/sessions.py, tests/test_sessions.py
If you have a passthrough environment and have passed `--no-install`, don't error because there's an `install` command that's not going to do anything.
Fixes #739. This fixes the underlying problem in #693 - that was asking for a way to detect `run("pip", "install", ...)` precisely because this bug kept `.install(...)` from being usable.
=> fix: don't error if not installing to passthrough

docs/config.rst, docs/tutorial.rst, docs/usage.rst, nox/sessions.py, nox/virtualenv.py, noxfile.py, tests/test_virtualenv.py
Adds micromamba support alongside the existing conda and mamba support. Micromamba is a version of mamba using C++ completely, not requiring Python. It's very useful for CI systems and anywhere a single binary is easier to work with.
Fix #680.
=> feat: add micromamba support

nox/command.py, nox/sessions.py, nox/virtualenv.py, tests/test_command.py, tests/test_sessions.py
Followup to #804. Setting `env={"NOCOLOR": None}` will unset the value if it exists in the outer environment.
=> feat: support None to remove envvars

nox/command.py, nox/popen.py, nox/sessions.py, tests/test_command.py, tests/test_sessions.py
Close #813. This provides better documentation, better signatures, and better static typing. This doesn't change too rapidly, so using `**` isn't that helpful. `**` is best for things that can't be determined statically.
A few kwargs that previously distinguished between not being passed and being passed now support `None`, which is simpler and also a little friendlier for callers.
> [!WARNING]
> This removes support for passing keyword arguments through to a function passed into run. `run(f, arg1, kw=kw)` is not supported anymore. This does keep support for `run(f, arg1)`. There's very little reason to ever do this, as it just runs the function for you with a smidge of logging. It's listed in the comment as a legacy feature. It was a little buggy before too, with `env=` for example being …
=> feat: use static arguments instead of **kwargs

nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py, tests/test_virtualenv.py
It's necessary sometimes to use the backend tool (pip, uv, conda, mamba, micromamba) inside a virtual environment. We already have a bit of special casing for it, making sure it's not considered "external". This PR just makes sure that `.run("uv", ...)` is always supported if you are using the uv backend. All the other backends are already gaurenteed to be on the path if they are active, so no change is needed (yet, anyway - this mechanism could also enable using `pip` from outside instead of always installing it, might be worth investigating in the future).
Followup to and generalizes #795.
=> fix: ensure 'uv' always works in a uv venv

.github/workflows/action.yml, noxfile.py
Python 3.8 & 3.9 are now supported on macOS-14.
=> chore(ci): use default action tests for macos-14

.github/workflows/ci.yml, CONTRIBUTING.md, action.yml, docs/conf.py, docs/config.rst, docs/tutorial.rst, docs/usage.rst, nox/_options.py, nox/_version.py, nox/command.py, nox/tox_to_nox.py, noxfile.py, pyproject.toml, tests/test_main.py, tests/test_virtualenv.py
Dropping support for running with Python 3.7, which is well past EoL.
=> chore: drop Python 3.7

.github/workflows/action.yml, action.yml
If uv has been installed before the nox action, use it to speed up the install of nox. Should save ~10 seconds or so.
=> chore: use uv if available in action

nox/command.py, nox/popen.py, nox/sessions.py
This is used, for example, by nox-poetry: https://github.com/cjolowicz/nox-poetry/blob/fb20b69892d394e8a4b97ae4d1f1d06cf811d32f/src/nox_poetry/poetry.py#L91
=> Update type annotation of `stderr` parameter to make it optional

CONTRIBUTING.md
=> fix: contribution guidelines

docs/config.rst, docs/tutorial.rst, nox/_decorators.py, nox/_parametrize.py, tests/resources/noxfile_tags.py, tests/test__option_set.py, tests/test__parametrize.py, tests/test_tasks.py
To allow more fine-grained session selection, allow tags to be set on individual parametrized sessions via either a tags argument to the `@nox.parametrize()` decorator, or a tags argument to `nox.param()` (similar to how parametrized session IDs can be specified). Any tags specified this way will be added to any tags passed to the `@nox.session()` decorator.
A couple of examples of how this could be used:
@nox.session
@nox.parametrize(
"db_engine", [
nox.param("sqlite", tags=["sqlite"])
nox.param("mysql", tags=["mysql"])
nox.param("postgresql", tags=["psql"])
]
)
@nox.parametrize(
"django", [
nox.param(">=3,<4", tags=["django3"])
nox.param(">=4,<5", tags=["django4"])
nox.param(">=5,<6", tags=["django5"])
]
)
def test(session, db_engine, django):
pass
In this case, a developer could run …
=> feat: allow setting tags on parametrized sessions

docs/cookbook.rst
Add missing cookbook recipe imports.
closes #852
=> fix: add missing cookbook recipe snippet imports

.pre-commit-config.yaml, CODE_OF_CONDUCT.md, nox/_decorators.py, nox/_option_set.py, nox/manifest.py, nox/registry.py, nox/virtualenv.py, pyproject.toml
=> chore: include 3.13 in classifiers

action.yml
Drop this from the default activation.
=> chore: PyPy no longer supports 3.9, so drop from action default list

nox/_options.py
logging is setup before all tasks,
so it's not possible to use it as noxfile.option.
we could add it after tasks.merge_noxfile_options, but in this case the logger wouldn't setup early for tasks.load_nox_module
=> fix: remove add_timestamp from noxfile.options

docs/tutorial.rst, nox/sessions.py, tests/resources/pep721example1.py, tests/test_sessions.py
See https://github.com/wntrblm/nox/issues/808#issuecomment-210613849. This makes using PEP 723 easier and more directly supported.
=> feat: install_and_run_script (PEP 721)

docs/usage.rst
Fix #840 with a note in the docs.
=> docs: note about uv reinstall

docs/cookbook.rst
Alternate to #857 for now, for #841.
=> docs: add uv sync example

.github/workflows/ci.yml, docs/tutorial.rst, nox/_decorators.py, nox/_resolver.py, nox/manifest.py, nox/registry.py, nox/sessions.py, nox/tasks.py, tests/resources/noxfile_requires.py, tests/test__parametrize.py, tests/test__resolver.py, tests/test_main.py, tests/test_sessions.py, tests/test_tasks.py
Hi! This adds session dependency resolution support to close #453 and as a prerequisite for #167. This implementation works and is fully tested, but this PR still needs some documentation and discussion.
To get a topological sort of the dependency graph, I haven't used `graphlib.TopologicalSorter` or [NetworkX DAG methods](https://networkx.org/documentation/stable/reference/algorithms/dag.html) because I don't think that such sorters can give nox the desired behavior. The problem, essentially, is that we don't just want any topological sorter but a specific (unique, hopefully) topological sort that the user can exert some ordering preference over. For example:
```python
@nox.session(python=False, requires=["c", "b"])
def a(session): pass
@nox.session(python=False)
def b(session): pass …
```
=> Support session dependencies (`requires`)

docs/tutorial.rst, nox/__init__.py, tests/test_main.py
See https://github.com/wntrblm/nox/issues/848. This just makes using PEP 723 a bit nicer, but doesn't implement native support in nox yet.
=> feat: expose main as nox.main

nox/_option_set.py, nox/_options.py, tests/test_main.py
Fix part of #869 - make sure only valid options are set.
The most recent commit also adds static typing for `nox.options`.
=> fix: error with helpful message if invalid option is set via nox.options

docs/config.rst, docs/tutorial.rst, nox/project.py, tests/test_project.py
=> feat: add helper to get the Python listing

.pre-commit-config.yaml, nox/project.py, pyproject.toml, tests/test_project.py
Starting work on https://github.com/wntrblm/nox/issues/845.
~~I was going to use @sirosen's dependency-groups, but it only supports 3.9+ - even the first version was 3.9+. I don't think that was a great idea for a foundational utility, but it's what it is. So we can't use it yet. And this is pretty easy, I think we can just write our own support as long as it's tested.~~
~~I've improved on the example implementation several ways: `setdefault` is a safer than `defaultdict`. I've used generators to remove the appends and extends. And I've used `*args` to simplify the past_groups handling.~~
I think we can start with a function like this, and maybe eventually come up with a nicer interface for things in pyproject.toml. But this is simple and could be used by the fancier interface later.
=> feat: helper to get dependency-groups

nox/sessions.py, tests/test_sessions.py
=> fix: error if invalid reuse_venv set

nox/__init__.py, nox/__main__.py, nox/_cli.py
Follow up to https://github.com/wntrblm/nox/pull/878, fixing a warning about `__main__` already being imported when running `__main__` (I think it messes with the `if __name__ == "__main__"` statement when you use `python -m nox` and that imports `__init__` and that triggers the `__main__` import early).
Fixed by moving `__main__.py` contents to `_cli.py` then importing from there for `__init__.py` and `__main__.py`. Backward compatible.
Noticed in #881.
=> fix: warning about __main__ already being imported

nox/sessions.py, nox/tasks.py, tests/resources/orig_dir/noxfile.py, tests/resources/sym_dir/noxfile.py, tests/test_main.py
Fix #828.
If you need the non-symlinked file, it's easy to get with `__file__`, as can be seen in the tests.
=> fix: support noxfile being a symlink

.pre-commit-config.yaml, nox/logger.py
Looks like these haven't been needed for a few years.
=> chore: drop some type ignores for colorlog

.pre-commit-config.yaml, nox/tox_to_nox.py, pyproject.toml
pkgutil is part of setuptools. Use standard and faster importlib.resources instead. Saves a few type ignores.
=> fix(tox-to-nox): switch pkgutil for importlib-resources

.pre-commit-config.yaml, nox/_option_set.py, pyproject.toml
This is a followup to #871. It also reduces the need for #872, as I think it makes it harder or impossible to incorrectly set this via normal means.
Attrs is a well respected, zero dependency, small library by a CPython core dev, but it is an extra dependency. If we did adopt it, though, I would start moving over a few other things, which could improve our internal typing too.
<details>
<summary>Incomplete list for "NoxCmdOptions":</summary>
```python
class NoxCmdOptions(NoxOptions):
version: bool
list_sessions: bool
json: bool
posargs: list[str]
add_timestamp: bool
no_venv: bool
R: bool
noxfile: str
envdir: None | str
extra_pythons: list[str]
force_pythons: list[str]
install_only: bool
no_install: bool
report: None | str
no_reuse_existing_virtualenvs: bool  # backcompat
non_interactive: …
```
=> fix: validate entries in nox.config, too, using attrs

.pre-commit-config.yaml, nox/_options.py, pyproject.toml, tests/conftest.py, tests/test_action_helper.py
Some packages now have types.
PyTest 7+ required now for `pythonpath`.
=> chore: more typing and test improvements

.pre-commit-config.yaml, nox/command.py, nox/manifest.py, nox/registry.py, nox/virtualenv.py, pyproject.toml, tests/test__option_set.py, tests/test__parametrize.py, tests/test__resolver.py, tests/test__version.py, tests/test_action_helper.py, tests/test_command.py, tests/test_logger.py, tests/test_main.py, tests/test_manifest.py, tests/test_project.py, tests/test_registry.py, tests/test_sessions.py, tests/test_tasks.py, tests/test_toml.py, tests/test_tox_to_nox.py, tests/test_virtualenv.py, tests/test_workflow.py
This fully statically types the test suite. This makes it easier to refactor, as mypy will help report changes. It also gives our current static typing a much better usage test, so some fixes for types are included.
=> tests: statically type tests

nox/tox_to_nox.py, nox/virtualenv.py, noxfile.py, pyproject.toml, tests/conftest.py, tests/test__version.py, tests/test_main.py, tests/test_tasks.py, tests/test_toml.py, tests/test_tox_to_nox.py, tests/test_virtualenv.py
Noticed when checking some Ruff preview stuff.
=> fix: include encoding for consistent behavior (default in Python 3.15+)

nox/command.py, tests/test_command.py, tests/test_sessions.py, tests/test_tox_to_nox.py, tests/test_virtualenv.py
Replace the deprecated `tmpdir` with `tmp_path`. Used the new static typing in tests to help find the needed updates for py.path (`LEGACY_PATH`) -> Path.
The which/run commands in `nox.command` now support `os.PathLike`.
=> tests: use tmp_path instead of tmpdir

nox/__init__.py, nox/__main__.py, nox/_cli.py, nox/_decorators.py, nox/_option_set.py, nox/_options.py, nox/_parametrize.py, nox/_resolver.py, nox/_typing.py, nox/_version.py, nox/command.py, nox/logger.py, nox/manifest.py, nox/popen.py, nox/registry.py, nox/sessions.py, nox/tasks.py, nox/tox_to_nox.py, nox/virtualenv.py, nox/workflow.py
Adding `__all__` and `def __dir__` everwhere so tab completion is clean. Using a trick I've not tried elsewhere to also include tab completion cleanup in `__init__`.
=> chore: limit the visible items for tab completion

nox/command.py, tests/test_command.py
Should fix #902 and our test suite, where 3.12 and 3.13 are failing.
=> tests: fix broken mock on CPython 3.12.8+

nox/virtualenv.py, noxfile.py, tests/test_command.py, tests/test_virtualenv.py
I believe this fixes #630 
... at least, I was able to remove the workaround I had in https://github.com/PyO3/setuptools-rust/pull/501
Open to alternative ideas / suggestions how you'd like this tested.
=> correct virtualenv bin dir under mingw python

nox/tox_to_nox.py, tests/test_tox_to_nox.py
=> fix: correctly separate command-line arguments in `tox-to-nox`

nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py, tests/test_virtualenv.py
Fix https://github.com/wntrblm/nox/issues/868. Two issues:
* Setting `include_outer_env=False` does nothing at all if `env=` is not passed. The outer env is still included.
* Required environment variables set by nox itself, like `VIRTUAL_ENV` (required for `uv`), and `CONDA_PREFIX` (required for conda-family) would not be included if you do set both.
Fixing this was a bit intrusive: now `.env` only is the local environment
settings, and removals are added to it using None. The type has changed to match `.command`, with the None possibility. And then the final environment is built in the `_run`, where it can correctly process things like adding the bin dir and filtering the None's.
=> fix: outer_env issues fixed

nox/virtualenv.py
=> Use `uv python install` only with uv backend

nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py
Helping with #881 which is tripping up over the test mocking. This pulled out this function to make it reusable and also improves the test mocking.
=> refactor: pull out env creation into helper method

.github/workflows/action.yml, nox/virtualenv.py, noxfile.py, tests/test_virtualenv.py
=> fix: allow pypy- to be used (matching GHA)

docs/tutorial.rst, nox/_cli.py, nox/_options.py, nox/project.py, nox/virtualenv.py, tests/resources/noxfile_script_mode.py, tests/test__cli.py, tests/test_main.py
I've started https://github.com/wntrblm/nox/issues/848. This allows you to write a noxfile like this:
```python
import nox
import numpy
@nox.session
def example(session: nox.Session) -> None:
print(numpy.__file__)
```
Any dependencies, including version ranges and nox, will be checked. If not satisfied, nox will make a new `.nox/_nox_script_mode` environment, set it up with the above dependencies, and then pass control to the new nox environment. Requires-python is not respected yet, might need https://github.com/wntrblm/nox/issues/814. That can be added later, not a target for this PR.
I've allowed this to be passed via flag and envvar, but envvar always comes first, and overrides the flag. This ensures the second run will never trigger a third run of nox. If someone has other ideas for …
=> feat: support PEP 723 noxfiles

.github/workflows/action.yml, action.yml
Close #915. Add an ARM runner, drop PyPy from the default list, which should also speed up non-ARM runs.
=> fix(gha): drop PyPy from the default list for the GitHub Action

nox/project.py
Close https://github.com/wntrblm/nox/issues/843. I was worried about nox's handling of the CWD but I think this is actually safe.
=> fix: add a pyproject.toml default for load_toml

nox/sessions.py, nox/virtualenv.py, tests/test_sessions.py
See https://github.com/wntrblm/nox/pull/818#issuecomment-2628118612.
=> fix: handle uvx like uv

nox/_option_set.py, tests/test__option_set.py
Lists were being over-validated when we added validation (see #920), `nox.options.sessions = ("a", "b")` should be allowed. I don't want to allow `nox.options.sessions = "ab"`, though, since that's surprising and would only work for one-letter sessions. ~~I went with just validating both lists and tuples~~, though now that I think of it, maybe sets should be supported too. There's also the option of just validating for Sequence + not(str), but that can't be represented in static types (first commit), as far as I know. Edit: reverted to the original Sequence idea, `set` and `frozenset` (at least) should be supported too.
=> fix: over validation of lists

nox/virtualenv.py, tests/test_virtualenv.py
Fix #919 by moving the `uv` version check up to the discovery phase, and skip discovery if the version step returns an error code. If we know what the minimum version of uv we support is, we could add that here.
=> fix: support broken uv (via pyenv)

.github/workflows/cd.yml, .github/workflows/ci.yml
This needs to be setup in PyPI as well. No need to make a `pypi` environment, it will be created automatically. Publishing a release triggers the deployment; you can add environment protection rules to requiressome number of maintainer approvals and such. Docs: https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/
You can download the SDist/wheel from any run, now, too.
Fields:
* Workflow name: `cd.yml`
* Environment name: `pypi`
=> ci: trusted publisher

docs/config.rst
The final example in the "Assigning tags to parametrized sessions" section was using `nox.param()` incorrectly.  Fix by passing the parameter values as positional arguments (rather than as a tuple), and passing the tags as a keyword argument.
=> docs: fix parametrized session tagging example

docs/usage.rst
This is no longer needed, `pip install .` now works as expected.
=> docs: uv now supports pip install . reinstallation

.github/action_helper.py, action.yml, noxfile.py, tests/test_action_helper.py
See #943.
This bumps the built-in version to 3.12, drops 3.8 from the default list, and adds 3.13 to the potential versions running our script.
=> fix: use Python 3.12 for action, allow 3.13, drop 3.8 from auto versions

nox/_options.py, nox/tasks.py, tests/test_tasks.py
=> feat: show skip reason by default

nox/_cli.py, tests/resources/noxfile_script_mode_url_req.py, tests/test__cli.py, tests/test_main.py
Fixes #934.
W.r.t. performance: On uv (the default, if available), uv caches based on the URL. On virtualenv however, the URL will get pulled and built/installed every time.
Ideally, for the virtualenv case, nox would do its own caching on the URL, similar to what the uv backend, `uv run -s noxfile.py` and `pipx run noxfile.py` all do. I have not included that here since I wanted to keep the scope of this PR to the correctness issue. Caching can be added later if needed. URL dependencies in PEP 723 noxfiles are perhaps not a very common case anyway, so perhaps it is TBD whether it's worth it for Nox to build a serialization format for doing said caching?
=> Never ignore URL dependencies in PEP 723 noxfiles

nox/virtualenv.py, tests/test_virtualenv.py
We don't support uv 0.7. This fixes it and also supports the UV environment variable, which wasn't something UV had before. (This fixes nested uv calls, uv sets UV when it calls anything)
=> fix: uv version is now uv self version, support UV

nox/_option_set.py, nox/_resolver.py, nox/manifest.py, nox/registry.py, tests/test_manifest.py
Part of the language officially since 3.7 (unofficially 3.6).
=> refactor: use dict instead of OrderedDict

tests/conftest.py
Pulled from #965, adds a little more protection for keeping the registry fresh.
=> tests: clear the registry

nox/_option_set.py, nox/tox_to_nox.py
This makes `--help` colorized on Python 3.14+. "Did you mean" suggestions are also added.
For all Pythons, abbreviations have been disabled. This is generally error prone, so I think it's better to avoid it. It works properly on 3.8+ (it causes some issues before that).
=> feat: color help on 3.14+ and suggestions, plus no abbrev

docs/index.rst
We've been using `nox` since https://github.com/Qiskit/rustworkx/pull/861 and overall the experience has been extremely smooth! Thanks for making this.
=> docs: add rustworkx as an example user

pyproject.toml
Fix for https://github.com/nedbat/coveragepy/issues/1983.
=> fix: hide new coverage warning on 3.14

nox/virtualenv.py, tests/test_virtualenv.py
We can't get rid of Conda-trash files on Windows, so let uv delete it. Might be faster too. It complains if you give it a non-empty directory without a `pyvenv.cfg` file in it.
=> fix: let uv replace the directory instead of deleting it ourselves

nox/logger.py
related: https://github.com/wntrblm/nox/pull/989#issuecomment-3054366659
nox tests run setup_logging() multiple times in a session and we end up with multiple duplicate handlers, some of which are already closed, fail and try to log the error, creating a cascade of logs
The change is making sure we get rid of our own handler before creating a new one
=> CI ensure there are no duplicate log handlers
