wntrblm/nox

.travis.yml, docs/config.rst, docs/tutorial.rst, docs/usage.rst, nox.py, nox/__init__.py, nox/_parametrize.py, nox/main.py, nox/session.py, tests/test__parametrize.py, tests/test_main.py, tests/test_session.py
=> Parametrize

nox/command.py, nox/main.py, nox/sessions.py, tests/test_sessions.py
See https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3135#discussion_r105708321
=> Change to the nox.py directory by default.

nox.py, setup.py
=> Test on Python 3.6

nox/virtualenv.py
=> Print virtualenv path when re-using virtualenv

nox/command.py, tests/test_command.py
Introduced by mistake as a fix to #28.
=> Fixing unintentional missed branch for env/env_fallback collision.

nox.py, nox/command.py, nox/main.py, nox/sessions.py, nox/virtualenv.py, tests/test__parametrize.py, tests/test_command.py, tests/test_main.py, tests/test_nox_to_tox.py, tests/test_registry.py, tests/test_sessions.py, tests/test_virtualenv.py
=> Add session.skip

nox/virtualenv.py
=> Use python -m virtualenv to invoke virtualenv

nox/virtualenv.py, tests/test_virtualenv.py
=> Blacklist problematic virtualenv environment variables

appveyor.yml
This way one failure stops the entire build.
=> Adding fast-finish to AppVeyor build matrix.

docs/usage.rst, nox/command.py, nox/sessions.py, tests/test_sessions.py
=> Don't skip install commands when re-using existing virtualenvs.

CONTRIBUTING.md
The stable version of nox doesn't work with the current `nox.py` file.
Also, the commands `nox --session "interpreters(version='3.6')"` don't work, or I misunderstood something
=> Update installation command in contributing

CONTRIBUTING.md
Following https://github.com/theacodes/nox/pull/101
=> Update test commands in contributing

nox/_testing.py, nox/main.py, nox/manifest.py, nox/sessions.py, nox/virtualenv.py
Python 2 support was dropped, not need no inherit from object.
=> Remove object inheritance

MANIFEST.in, setup.py
Ref https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls
=> Show additional links on pypi

docs/index.rst
@lukesneeringer @dhermes @stsewd please let me know if you *don't* want to be mentioned here.
(& ofc, thank you for contributing so much!)
=> Add contributors

nox.py
Related to https://github.com/theacodes/nox/pull/111#issuecomment-415483617
=> Run sphinx with -W option

.readthedocs.yml, nox.py
I just tried to keep the current behavior, hope it's fine :)
Close #102
=> Use a rtd conf file

nox/virtualenv.py, tests/test_virtualenv.py
Also cache and re-use the result.
=> Don't modify `Virtualenv.interpreter` in `_resolved_interpreter`.

docs/usage.rst
=> Fix function name on docs

docs/index.rst, docs/tutorial.rst, docs/usage.rst
Ref: https://github.com/tox-dev/tox/issues/1088
=> Fix tox casing to be consistent with their docs, remove . from pytest

docs/tutorial.rst, nox/__init__.py, nox/_parametrize.py, noxfile.py, tests/test__parametrize.py
=> Add the ability to give parametrized sessions a custom ID

docs/_static/custom.css
(I hate CSS and at this point I want to just completely move away from Alabaster to something based on Bulma)
=> Fix some CSS issues on mobile

.travis.yml, noxfile.py
I don't have 3.6 in my OS by default anymore, guessing the same for others
=> Update noxfile to use python3.7

docs/tutorial.rst
Hey nice project - keep up the good work :)
=> fix grammar

nox/command.py, tests/test_command.py
Drop some python 2 code and a typo in the docstring
=> Update commands module

docs/index.rst
I resisted the urge to add our project to the top of the list :grin: , so I alphabetically sorted and then added our project.
If the list order was important as is was, please let me know after which project you'd like ours to be added.
=> Add Salt to the list of projects that use Nox.

docs/tutorial.rst
Follow-up to PR #217 and issue #183.
=> Add conda docs to tutorial.

tests/test_virtualenv.py
Amends PR #224 to add some code documentation to its test fixtures.
@theacodes As discussed at https://github.com/theacodes/nox/pull/224#issuecomment-522253907
Motivation: to help maintainability/clarity of that PR's tests.
=> Document complex test_virtualenv fixtures

nox/registry.py, nox/sessions.py, nox/virtualenv.py
Session parameter venv_params has been added as an optional list for virtualenv, venv and conda backends
=> Added venv params

nox/_options.py, nox/manifest.py, nox/sessions.py, nox/tasks.py, tests/test_manifest.py, tests/test_sessions.py
Hey, here's another PR removing more of these comments. From #292 I have fixed 1.3, 2.1, 2.3 and many from 2.2.  
This leaves 1.6 and 2.2 to be removed.
=> Remove more type ignore comments

noxfile.py
=> Typo - formater to formatter

nox/virtualenv.py
Fix overwritten and environment typos in virtualenv.py
=> Fix overwritten and environment typos in virtualenv.py

docs/usage.rst
=> Typo: Controling -> Controlling

nox/__init__.py
=> Export `Session` in `__init__`

docs/tutorial.rst
=> Fix typo in Tutorial

MANIFEST.in
Closes #336 
@theacodes Please review :)
=> Add py.typed to manifest.in

nox/command.py, nox/virtualenv.py, tests/test_logger.py
Run the blacken session on the codebase.
=> Sort imports using isort

CHANGELOG.md, setup.py
Thought we could round out the year with a new release :)
=> Release 2020.12.31

.github/workflows/ci.yml
Followup to #458, dropping some extra lines.
=> ci: simpler build

nox/_decorators.py, nox/_typing.py
Fixes #507. Please tell me if there're more missing notices to add.
=> Add missing copyright notices

docs/index.rst
cc @theacodes
Also, is anybody missing on the list? Tell me, and I can add them ;)
=> Add my name to the documentation index as a collaborator

docs/index.rst
Update the list of maintainers to include @FollowTheProcess and myself.
=> Update the list of maintainers

.readthedocs.yml
Following https://docs.readthedocs.io/en/stable/config-file/v2.html and https://github.com/theacodes/nox/pull/496#issuecomment-937890083.
=> Use the new ReadTheDocs configurations

.github/workflows/ci.yml
=> ci: fix missing 3.8 -> 3.9 for CI

requirements-test.txt
Closes #559.
I have a couple of followup ideas, but this should at least get the docs building again.
=> docs: fix readthedocs

requirements-conda-test.txt, setup.cfg
=> Support argcomplete v2

.pre-commit-config.yaml, pyproject.toml, setup.cfg
Several minor touchups too small on their own.
- chore: remove wheel
- chore: include flake8-bugbear's extra checks
- chore: fix pycln's arg in pre-commit
=> chore: minor touchups

.pre-commit-config.yaml
This PR updates all the pre-commit hooks in `.pre-commit-config.yaml` to their latest versions
=> Autoupdate pre-commit hooks

.github/workflows/action.yml
=> Remove macos-10.15 from Github Action

docs/tutorial.rst
=> Fix typo in tutorial.rst

docs/cookbook.rst
Follow up to #665 based on https://github.com/scikit-build/scikit-build-sample-projects/pull/31.
=> docs: recipe for GHA generate

nox/_decorators.py, nox/registry.py
=> chore: save session name in `Func`

.github/workflows/action.yml, .github/workflows/ci.yml, action.yml
=> chore(ci): bump actions/setup-python & conda-incubator/setup-miniconda

tests/conftest.py
=> Allow tests to pass in environments where NO_COLOR=1 is set

CHANGELOG.md, pyproject.toml
The changelog is essentially generated by GitHub Release, which I've quickly classified by type. If anybody wants to improve the descriptions (they'd benefit), please go ahead 😉
=> Release 2024.03.02

docs/usage.rst
=> docs: workaround no longer needed

nox/virtualenv.py
=> fix: disallow UV_SYSTEM_PYTHON

.github/workflows/ci.yml, tests/test_virtualenv.py
ARM is fine, 3.8 and 3.9 missing is not.
=> ci: macos-latest now is macos-14

nox/sessions.py
=> docs: add warning about uv and local packages

docs/cookbook.rst
- Corrected typos in the `cookbook.rst`.
=> Typo-fix in Cookbook

.github/workflows/action.yml, action.yml
=> chore: add 3.13 to the action defaults

.github/workflows/ci.yml
Fix CI. Mambaforge no longer supported.
=> ci: use miniforge

.github/workflows/action.yml
Doesn't annotate every run with "no version pinned". :)
=> ci: use astral-sh's setup-uv

nox/tasks.py
This is just the cleanup part of #829, without the logic change. I think that it would be good to put this in, then decide on that one.
=> chore: cleanup symlink noxfile code

nox/__init__.py, nox/_option_set.py, nox/_parametrize.py, nox/command.py, nox/sessions.py, nox/virtualenv.py, pyproject.toml, tests/test_sessions.py, tests/test_virtualenv.py
- **chore: add a few nox checks**
- **chore: add a few things from preview ruff**
=> chore: some extra simplifications from Ruff

.pre-commit-config.yaml, pyproject.toml
Adding orjson for faster mypy.
=> chore: bump pre-commit

nox/virtualenv.py
https://github.com/wntrblm/nox/issues/907
=> catch PermissionError from popen when UV is not installed

.github/release.yml, .github/workflows/action.yml, .github/workflows/ci.yml
Adding a few suggestions from zizmor, and also adding a release.yml for better release note generation.
=> ci: add some suggestions from zizmor

CHANGELOG.md
=> docs: prepare for first 2025 release

nox/_option_set.py, nox/_options.py, tests/test__option_set.py
=> fix: support Path for envdir

tests/test_main.py, tests/test_tox_to_nox.py
=> tests: make skips a bit smarter

docs/cookbook.rst
=> docs: update uv recipe

pyproject.toml
Also some minor touchups suggested by sp-repo-review.
=> chore: use PEP 639 license

nox/virtualenv.py
=> fix: add UV_PYTHON to disallowed vars

nox/manifest.py, tests/resources/noxfile_parametrize.py, tests/test_main.py
Fix https://github.com/wntrblm/nox/issues/949.
=> fix: support forcing Python on parametrized session

.github/workflows/ci.yml, nox/sessions.py, noxfile.py, tests/test_sessions.py, tests/test_virtualenv.py
=> fix: conda_install issue with newer conda

CHANGELOG.md, pyproject.toml
=> chore: bump version to 2025.05.01

.github/workflows/action.yml, .github/workflows/ci.yml
=> ci: modernize and remove rc conda channel

nox/_decorators.py, nox/sessions.py, pyproject.toml
This makes debugging errors easier.
=> chore: add better reprs for some internal classes

.github/workflows/ci.yml, noxfile.py, pyproject.toml, tests/test_virtualenv.py
Fix #961. Test the minimums and update to fix tests.
=> fix: correct minimum versions and test

.github/workflows/ci.yml, pyproject.toml
=> chore: add 3.14 beta 1 support

.github/workflows/ci.yml
This shouldn't be just doing the same thing again (see #981).
=> ci: restore minimums test

.github/workflows/action.yml
=> ci: drop Windows 2019
